import type { StudioState } from '@mui/x-studio';
import {
  CUSTOMERS_SOURCE_ID,
  customersSource,
  customersBindings,
  ORDERS_SOURCE_ID,
  ordersSource,
  ordersBindings,
  ORDER_ITEMS_SOURCE_ID,
  orderItemsSource,
  orderItemsBindings,
  PRODUCTS_SOURCE_ID,
  productsSource,
} from '../data';

export const INITIAL_STATE: Partial<StudioState> = {
  dashboard: {
    id: 'dashboard-sales',
    title: 'Sales Dashboard',
    activePageId: 'page-1',
  },
  pages: {
    'page-1': {
      id: 'page-1',
      title: 'Overview',
      widgetRows: [
        ['widget-kpi-revenue', 'widget-kpi-orders', 'widget-kpi-customers'],
        ['widget-chart-category', 'widget-chart-country'],
        ['widget-orders-grid'],
      ],
    },
    'page-2': {
      id: 'page-2',
      title: 'Details',
      widgetRows: [],
    },
  },
  dataSources: {
    [PRODUCTS_SOURCE_ID]: productsSource,
    [CUSTOMERS_SOURCE_ID]: customersSource,
    [ORDERS_SOURCE_ID]: ordersSource,
    [ORDER_ITEMS_SOURCE_ID]: orderItemsSource,
  },
  relationships: [
    {
      id: 'rel-orders-customers',
      sourceId: ORDERS_SOURCE_ID,
      sourceField: 'customerId',
      targetId: CUSTOMERS_SOURCE_ID,
      targetField: 'id',
      type: 'many-to-one',
    },
    {
      id: 'rel-orderitems-orders',
      sourceId: ORDER_ITEMS_SOURCE_ID,
      sourceField: 'orderId',
      targetId: ORDERS_SOURCE_ID,
      targetField: 'id',
      type: 'many-to-one',
    },
  ],
  widgets: {
    'widget-kpi-revenue': {
      id: 'widget-kpi-revenue',
      kind: 'kpi',
      title: 'Total Revenue',
      sourceId: ORDER_ITEMS_SOURCE_ID,
      layout: { x: 0, y: 0, width: 4, height: 3 },
      bindings: orderItemsBindings,
      config: {
          kpiValueField: 'total',
          kpiAggregation: 'sum',
          kpiSparkline: true,
          kpiSparklineField: 'date',
          kpiSparklineSourceId: ORDERS_SOURCE_ID,
          kpiSparklineCumulative: true,
        },
    },
    'widget-kpi-orders': {
      id: 'widget-kpi-orders',
      kind: 'kpi',
      title: 'Total Orders',
      sourceId: ORDERS_SOURCE_ID,
      layout: { x: 4, y: 0, width: 4, height: 3 },
      bindings: ordersBindings,
      config: {
          kpiValueField: 'status',
          kpiAggregation: 'count',
          kpiSparkline: true,
          kpiSparklineField: 'date',
        },
    },
    'widget-kpi-customers': {
      id: 'widget-kpi-customers',
      kind: 'kpi',
      title: 'Active Customers',
      sourceId: CUSTOMERS_SOURCE_ID,
      layout: { x: 8, y: 0, width: 4, height: 3 },
      bindings: customersBindings,
      config: { kpiValueField: 'company', kpiAggregation: 'count' },
    },
    'widget-chart-category': {
      id: 'widget-chart-category',
      kind: 'chart',
      title: 'Revenue by Category',
      sourceId: ORDER_ITEMS_SOURCE_ID,
      layout: { x: 0, y: 3, width: 6, height: 6 },
      bindings: orderItemsBindings,
      config: { chartType: 'bar', xField: 'category', yField: 'total' },
    },
    'widget-chart-country': {
      id: 'widget-chart-country',
      kind: 'chart',
      title: 'Revenue by Country',
      sourceId: ORDERS_SOURCE_ID,
      layout: { x: 6, y: 3, width: 6, height: 6 },
      bindings: ordersBindings,
      config: { chartType: 'pie', xField: 'country', yField: 'total' },
    },
    'widget-orders-grid': {
      id: 'widget-orders-grid',
      kind: 'grid',
      title: 'Recent Orders',
      sourceId: ORDERS_SOURCE_ID,
      layout: { x: 0, y: 9, width: 12, height: 8 },
      bindings: ordersBindings,
      config: { columns: ['id', 'date', 'customerId', 'status'] },
    },
  },
  shell: {
    // TODO: make these optional
    openDrawers: { data: false, compose: true, filters: true },
    selectedWidgetId: null,
    selectedFieldId: null,
    selectedSourceId: null,
  },
};
