/**
 * Normalizes country identifiers (ISO alpha-2, alpha-3, full name, or common alias)
 * to ISO 3166-1 alpha-2 codes for lookup in the world map.
 *
 * Also provides US state normalization and geographic constants used by the
 * geography loaders.
 *
 * Normalization is deterministic — no fuzzy matching.
 */

/** ISO alpha-3 → alpha-2 mapping for the ~195 UN member states. */
const ALPHA3_TO_ALPHA2: Record<string, string> = {
  AFG: 'AF',
  ALB: 'AL',
  DZA: 'DZ',
  AND: 'AD',
  AGO: 'AO',
  ATG: 'AG',
  ARG: 'AR',
  ARM: 'AM',
  AUS: 'AU',
  AUT: 'AT',
  AZE: 'AZ',
  BHS: 'BS',
  BHR: 'BH',
  BGD: 'BD',
  BRB: 'BB',
  BLR: 'BY',
  BEL: 'BE',
  BLZ: 'BZ',
  BEN: 'BJ',
  BTN: 'BT',
  BOL: 'BO',
  BIH: 'BA',
  BWA: 'BW',
  BRA: 'BR',
  BRN: 'BN',
  BGR: 'BG',
  BFA: 'BF',
  BDI: 'BI',
  CPV: 'CV',
  KHM: 'KH',
  CMR: 'CM',
  CAN: 'CA',
  CAF: 'CF',
  TCD: 'TD',
  CHL: 'CL',
  CHN: 'CN',
  COL: 'CO',
  COM: 'KM',
  COD: 'CD',
  COG: 'CG',
  CRI: 'CR',
  CIV: 'CI',
  HRV: 'HR',
  CUB: 'CU',
  CYP: 'CY',
  CZE: 'CZ',
  DNK: 'DK',
  DJI: 'DJ',
  DOM: 'DO',
  ECU: 'EC',
  EGY: 'EG',
  SLV: 'SV',
  GNQ: 'GQ',
  ERI: 'ER',
  EST: 'EE',
  ETH: 'ET',
  FJI: 'FJ',
  FIN: 'FI',
  FRA: 'FR',
  GAB: 'GA',
  GMB: 'GM',
  GEO: 'GE',
  DEU: 'DE',
  GHA: 'GH',
  GRC: 'GR',
  GRD: 'GD',
  GTM: 'GT',
  GIN: 'GN',
  GNB: 'GW',
  GUY: 'GY',
  HTI: 'HT',
  HND: 'HN',
  HUN: 'HU',
  ISL: 'IS',
  IND: 'IN',
  IDN: 'ID',
  IRN: 'IR',
  IRQ: 'IQ',
  IRL: 'IE',
  ISR: 'IL',
  ITA: 'IT',
  JAM: 'JM',
  JPN: 'JP',
  JOR: 'JO',
  KAZ: 'KZ',
  KEN: 'KE',
  PRK: 'KP',
  KOR: 'KR',
  KWT: 'KW',
  KGZ: 'KG',
  LAO: 'LA',
  LVA: 'LV',
  LBN: 'LB',
  LSO: 'LS',
  LBR: 'LR',
  LBY: 'LY',
  LTU: 'LT',
  LUX: 'LU',
  MDG: 'MG',
  MWI: 'MW',
  MYS: 'MY',
  MDV: 'MV',
  MLI: 'ML',
  MRT: 'MR',
  MUS: 'MU',
  MEX: 'MX',
  MNG: 'MN',
  MNE: 'ME',
  MAR: 'MA',
  MOZ: 'MZ',
  MMR: 'MM',
  NAM: 'NA',
  NPL: 'NP',
  NLD: 'NL',
  NZL: 'NZ',
  NIC: 'NI',
  NER: 'NE',
  NGA: 'NG',
  MKD: 'MK',
  NOR: 'NO',
  OMN: 'OM',
  PAK: 'PK',
  PAN: 'PA',
  PNG: 'PG',
  PRY: 'PY',
  PER: 'PE',
  PHL: 'PH',
  POL: 'PL',
  PRT: 'PT',
  QAT: 'QA',
  ROU: 'RO',
  RUS: 'RU',
  RWA: 'RW',
  KNA: 'KN',
  LCA: 'LC',
  VCT: 'VC',
  WSM: 'WS',
  STP: 'ST',
  SAU: 'SA',
  SEN: 'SN',
  SRB: 'RS',
  SLE: 'SL',
  SGP: 'SG',
  SVK: 'SK',
  SVN: 'SI',
  SLB: 'SB',
  SOM: 'SO',
  ZAF: 'ZA',
  SSD: 'SS',
  ESP: 'ES',
  LKA: 'LK',
  SDN: 'SD',
  SUR: 'SR',
  SWZ: 'SZ',
  SWE: 'SE',
  CHE: 'CH',
  SYR: 'SY',
  TWN: 'TW',
  TJK: 'TJ',
  TZA: 'TZ',
  THA: 'TH',
  TLS: 'TL',
  TGO: 'TG',
  TTO: 'TT',
  TUN: 'TN',
  TUR: 'TR',
  TKM: 'TM',
  UGA: 'UG',
  UKR: 'UA',
  ARE: 'AE',
  GBR: 'GB',
  USA: 'US',
  URY: 'UY',
  UZB: 'UZ',
  VUT: 'VU',
  VEN: 'VE',
  VNM: 'VN',
  YEM: 'YE',
  ZMB: 'ZM',
  ZWE: 'ZW',
  DMA: 'DM',
  SYC: 'SC',
  MDV_: 'MV',
};

/** Common English country name / alias → alpha-2 mapping. */
const NAME_TO_ALPHA2: Record<string, string> = {
  afghanistan: 'AF',
  albania: 'AL',
  algeria: 'DZ',
  angola: 'AO',
  argentina: 'AR',
  armenia: 'AM',
  australia: 'AU',
  austria: 'AT',
  azerbaijan: 'AZ',
  bahamas: 'BS',
  bahrain: 'BH',
  bangladesh: 'BD',
  barbados: 'BB',
  belarus: 'BY',
  belgium: 'BE',
  belize: 'BZ',
  benin: 'BJ',
  bhutan: 'BT',
  bolivia: 'BO',
  bosnia: 'BA',
  'bosnia and herzegovina': 'BA',
  botswana: 'BW',
  brazil: 'BR',
  brunei: 'BN',
  bulgaria: 'BG',
  'burkina faso': 'BF',
  burundi: 'BI',
  'cabo verde': 'CV',
  'cape verde': 'CV',
  cambodia: 'KH',
  cameroon: 'CM',
  canada: 'CA',
  'central african republic': 'CF',
  chad: 'TD',
  chile: 'CL',
  china: 'CN',
  colombia: 'CO',
  comoros: 'KM',
  congo: 'CG',
  'dr congo': 'CD',
  'democratic republic of the congo': 'CD',
  'republic of the congo': 'CG',
  'costa rica': 'CR',
  'ivory coast': 'CI',
  "cote d'ivoire": 'CI',
  croatia: 'HR',
  cuba: 'CU',
  cyprus: 'CY',
  'czech republic': 'CZ',
  czechia: 'CZ',
  denmark: 'DK',
  djibouti: 'DJ',
  'dominican republic': 'DO',
  ecuador: 'EC',
  egypt: 'EG',
  'el salvador': 'SV',
  'equatorial guinea': 'GQ',
  eritrea: 'ER',
  estonia: 'EE',
  eswatini: 'SZ',
  swaziland: 'SZ',
  ethiopia: 'ET',
  fiji: 'FJ',
  finland: 'FI',
  france: 'FR',
  gabon: 'GA',
  gambia: 'GM',
  georgia: 'GE',
  germany: 'DE',
  ghana: 'GH',
  greece: 'GR',
  grenada: 'GD',
  guatemala: 'GT',
  guinea: 'GN',
  'guinea-bissau': 'GW',
  guyana: 'GY',
  haiti: 'HT',
  honduras: 'HN',
  hungary: 'HU',
  iceland: 'IS',
  india: 'IN',
  indonesia: 'ID',
  iran: 'IR',
  iraq: 'IQ',
  ireland: 'IE',
  israel: 'IL',
  italy: 'IT',
  jamaica: 'JM',
  japan: 'JP',
  jordan: 'JO',
  kazakhstan: 'KZ',
  kenya: 'KE',
  'north korea': 'KP',
  'south korea': 'KR',
  korea: 'KR',
  kuwait: 'KW',
  kyrgyzstan: 'KG',
  laos: 'LA',
  latvia: 'LV',
  lebanon: 'LB',
  lesotho: 'LS',
  liberia: 'LR',
  libya: 'LY',
  lithuania: 'LT',
  luxembourg: 'LU',
  madagascar: 'MG',
  malawi: 'MW',
  malaysia: 'MY',
  maldives: 'MV',
  mali: 'ML',
  mauritania: 'MR',
  mauritius: 'MU',
  mexico: 'MX',
  moldova: 'MD',
  mongolia: 'MN',
  montenegro: 'ME',
  morocco: 'MA',
  mozambique: 'MZ',
  myanmar: 'MM',
  burma: 'MM',
  namibia: 'NA',
  nepal: 'NP',
  netherlands: 'NL',
  'new zealand': 'NZ',
  nicaragua: 'NI',
  niger: 'NE',
  nigeria: 'NG',
  'north macedonia': 'MK',
  macedonia: 'MK',
  norway: 'NO',
  oman: 'OM',
  pakistan: 'PK',
  panama: 'PA',
  'papua new guinea': 'PG',
  paraguay: 'PY',
  peru: 'PE',
  philippines: 'PH',
  poland: 'PL',
  portugal: 'PT',
  qatar: 'QA',
  romania: 'RO',
  russia: 'RU',
  'russian federation': 'RU',
  rwanda: 'RW',
  'saudi arabia': 'SA',
  senegal: 'SN',
  serbia: 'RS',
  'sierra leone': 'SL',
  singapore: 'SG',
  slovakia: 'SK',
  slovenia: 'SI',
  'solomon islands': 'SB',
  somalia: 'SO',
  'south africa': 'ZA',
  'south sudan': 'SS',
  spain: 'ES',
  'sri lanka': 'LK',
  sudan: 'SD',
  suriname: 'SR',
  sweden: 'SE',
  switzerland: 'CH',
  syria: 'SY',
  taiwan: 'TW',
  tajikistan: 'TJ',
  tanzania: 'TZ',
  thailand: 'TH',
  'timor-leste': 'TL',
  'east timor': 'TL',
  togo: 'TG',
  'trinidad and tobago': 'TT',
  tunisia: 'TN',
  turkey: 'TR',
  turkmenistan: 'TM',
  uganda: 'UG',
  ukraine: 'UA',
  'united arab emirates': 'AE',
  uae: 'AE',
  'united kingdom': 'GB',
  uk: 'GB',
  'great britain': 'GB',
  'united states': 'US',
  usa: 'US',
  us: 'US',
  america: 'US',
  'united states of america': 'US',
  uruguay: 'UY',
  uzbekistan: 'UZ',
  vanuatu: 'VU',
  venezuela: 'VE',
  vietnam: 'VN',
  'viet nam': 'VN',
  yemen: 'YE',
  zambia: 'ZM',
  zimbabwe: 'ZW',
};

/**
 * Normalizes a country identifier string to ISO 3166-1 alpha-2.
 *
 * Handles:
 * - ISO alpha-2 codes ("US", "gb", "de")
 * - ISO alpha-3 codes ("USA", "GBR", "DEU")
 * - Common English country names ("United States", "Germany")
 * - Some common aliases ("America", "UK")
 *
 * Returns the alpha-2 code (upper-case) or `null` if unknown.
 */
export function normalizeToAlpha2(value: unknown): string | null {
  if (typeof value !== 'string') {
    return null;
  }
  const trimmed = value.trim();
  if (!trimmed) {
    return null;
  }

  const upper = trimmed.toUpperCase();
  const lower = trimmed.toLowerCase();

  // Full name / alias lookup first — handles non-standard codes like "UK" → "GB",
  // "Burma" → "MM", etc. Must run before the 2-letter shortcut so that aliases
  // like "UK" (not a valid ISO alpha-2) are resolved correctly.
  const fromName = NAME_TO_ALPHA2[lower];
  if (fromName) {
    return fromName;
  }

  // Looks like a valid ISO alpha-2 code?
  if (upper.length === 2 && /^[A-Z]{2}$/.test(upper)) {
    return upper;
  }

  // Alpha-3?
  if (upper.length === 3 && /^[A-Z]{3}$/.test(upper)) {
    const a2 = ALPHA3_TO_ALPHA2[upper];
    if (a2) {
      return a2;
    }
  }

  return null;
}

// ─── ISO numeric → alpha-2 ─────────────────────────────────────────────────

/**
 * ISO 3166-1 numeric → alpha-2 mapping used to decode `world-atlas` feature IDs.
 * Keys are the numeric integer codes; values are upper-case alpha-2 codes.
 */
export const NUMERIC_TO_ALPHA2: Record<number, string> = {
  4: 'AF',
  8: 'AL',
  12: 'DZ',
  16: 'AS',
  20: 'AD',
  24: 'AO',
  28: 'AG',
  31: 'AZ',
  32: 'AR',
  36: 'AU',
  40: 'AT',
  44: 'BS',
  48: 'BH',
  50: 'BD',
  51: 'AM',
  52: 'BB',
  56: 'BE',
  60: 'BM',
  64: 'BT',
  68: 'BO',
  70: 'BA',
  72: 'BW',
  76: 'BR',
  84: 'BZ',
  90: 'SB',
  96: 'BN',
  100: 'BG',
  104: 'MM',
  108: 'BI',
  112: 'BY',
  116: 'KH',
  120: 'CM',
  124: 'CA',
  132: 'CV',
  140: 'CF',
  144: 'LK',
  148: 'TD',
  152: 'CL',
  156: 'CN',
  158: 'TW',
  170: 'CO',
  174: 'KM',
  178: 'CG',
  180: 'CD',
  188: 'CR',
  191: 'HR',
  192: 'CU',
  196: 'CY',
  203: 'CZ',
  204: 'BJ',
  208: 'DK',
  212: 'DM',
  214: 'DO',
  218: 'EC',
  222: 'SV',
  226: 'GQ',
  231: 'ET',
  232: 'ER',
  233: 'EE',
  238: 'FK',
  242: 'FJ',
  246: 'FI',
  250: 'FR',
  260: 'TF',
  262: 'DJ',
  266: 'GA',
  268: 'GE',
  270: 'GM',
  275: 'PS',
  276: 'DE',
  288: 'GH',
  300: 'GR',
  304: 'GL',
  308: 'GD',
  320: 'GT',
  324: 'GN',
  328: 'GY',
  332: 'HT',
  340: 'HN',
  348: 'HU',
  352: 'IS',
  356: 'IN',
  360: 'ID',
  364: 'IR',
  368: 'IQ',
  372: 'IE',
  376: 'IL',
  380: 'IT',
  384: 'CI',
  388: 'JM',
  392: 'JP',
  398: 'KZ',
  400: 'JO',
  404: 'KE',
  408: 'KP',
  410: 'KR',
  414: 'KW',
  417: 'KG',
  418: 'LA',
  422: 'LB',
  426: 'LS',
  428: 'LV',
  430: 'LR',
  434: 'LY',
  440: 'LT',
  442: 'LU',
  450: 'MG',
  454: 'MW',
  458: 'MY',
  462: 'MV',
  466: 'ML',
  474: 'MQ',
  478: 'MR',
  480: 'MU',
  484: 'MX',
  496: 'MN',
  498: 'MD',
  499: 'ME',
  504: 'MA',
  508: 'MZ',
  512: 'OM',
  516: 'NA',
  524: 'NP',
  528: 'NL',
  540: 'NC',
  548: 'VU',
  554: 'NZ',
  558: 'NI',
  562: 'NE',
  566: 'NG',
  578: 'NO',
  586: 'PK',
  591: 'PA',
  598: 'PG',
  600: 'PY',
  604: 'PE',
  608: 'PH',
  616: 'PL',
  620: 'PT',
  624: 'GW',
  626: 'TL',
  630: 'PR',
  634: 'QA',
  642: 'RO',
  643: 'RU',
  646: 'RW',
  659: 'KN',
  662: 'LC',
  670: 'VC',
  678: 'ST',
  682: 'SA',
  686: 'SN',
  688: 'RS',
  690: 'SC',
  694: 'SL',
  703: 'SK',
  704: 'VN',
  705: 'SI',
  706: 'SO',
  710: 'ZA',
  716: 'ZW',
  724: 'ES',
  728: 'SS',
  729: 'SD',
  732: 'EH',
  740: 'SR',
  748: 'SZ',
  752: 'SE',
  756: 'CH',
  760: 'SY',
  762: 'TJ',
  764: 'TH',
  768: 'TG',
  780: 'TT',
  784: 'AE',
  788: 'TN',
  792: 'TR',
  795: 'TM',
  800: 'UG',
  804: 'UA',
  807: 'MK',
  818: 'EG',
  826: 'GB',
  834: 'TZ',
  840: 'US',
  854: 'BF',
  858: 'UY',
  860: 'UZ',
  862: 'VE',
  887: 'YE',
  894: 'ZM',
  10: 'AQ', // Antarctica
};

// ─── US states (FIPS → abbreviation) ─────────────────────────────────────────

/**
 * US Census FIPS state code → 2-letter postal abbreviation.
 * Keys are the zero-padded FIPS string (as stored in `us-atlas` feature IDs).
 */
export const FIPS_TO_STATE_ABBR: Record<string, string> = {
  '01': 'AL',
  '02': 'AK',
  '04': 'AZ',
  '05': 'AR',
  '06': 'CA',
  '08': 'CO',
  '09': 'CT',
  '10': 'DE',
  '11': 'DC',
  '12': 'FL',
  '13': 'GA',
  '15': 'HI',
  '16': 'ID',
  '17': 'IL',
  '18': 'IN',
  '19': 'IA',
  '20': 'KS',
  '21': 'KY',
  '22': 'LA',
  '23': 'ME',
  '24': 'MD',
  '25': 'MA',
  '26': 'MI',
  '27': 'MN',
  '28': 'MS',
  '29': 'MO',
  '30': 'MT',
  '31': 'NE',
  '32': 'NV',
  '33': 'NH',
  '34': 'NJ',
  '35': 'NM',
  '36': 'NY',
  '37': 'NC',
  '38': 'ND',
  '39': 'OH',
  '40': 'OK',
  '41': 'OR',
  '42': 'PA',
  '44': 'RI',
  '45': 'SC',
  '46': 'SD',
  '47': 'TN',
  '48': 'TX',
  '49': 'UT',
  '50': 'VT',
  '51': 'VA',
  '53': 'WA',
  '54': 'WV',
  '55': 'WI',
  '56': 'WY',
  '60': 'AS',
  '66': 'GU',
  '69': 'MP',
  '72': 'PR',
  '78': 'VI',
};

/** Full US state/territory name → 2-letter abbreviation. */
const STATE_NAME_TO_ABBR: Record<string, string> = {
  alabama: 'AL',
  alaska: 'AK',
  arizona: 'AZ',
  arkansas: 'AR',
  california: 'CA',
  colorado: 'CO',
  connecticut: 'CT',
  delaware: 'DE',
  'district of columbia': 'DC',
  florida: 'FL',
  georgia: 'GA',
  hawaii: 'HI',
  idaho: 'ID',
  illinois: 'IL',
  indiana: 'IN',
  iowa: 'IA',
  kansas: 'KS',
  kentucky: 'KY',
  louisiana: 'LA',
  maine: 'ME',
  maryland: 'MD',
  massachusetts: 'MA',
  michigan: 'MI',
  minnesota: 'MN',
  mississippi: 'MS',
  missouri: 'MO',
  montana: 'MT',
  nebraska: 'NE',
  nevada: 'NV',
  'new hampshire': 'NH',
  'new jersey': 'NJ',
  'new mexico': 'NM',
  'new york': 'NY',
  'north carolina': 'NC',
  'north dakota': 'ND',
  ohio: 'OH',
  oklahoma: 'OK',
  oregon: 'OR',
  pennsylvania: 'PA',
  'rhode island': 'RI',
  'south carolina': 'SC',
  'south dakota': 'SD',
  tennessee: 'TN',
  texas: 'TX',
  utah: 'UT',
  vermont: 'VT',
  virginia: 'VA',
  washington: 'WA',
  'west virginia': 'WV',
  wisconsin: 'WI',
  wyoming: 'WY',
  'american samoa': 'AS',
  guam: 'GU',
  'puerto rico': 'PR',
  'u.s. virgin islands': 'VI',
  'virgin islands': 'VI',
  'northern mariana islands': 'MP',
};

/**
 * Normalizes a US state identifier to a 2-letter postal abbreviation.
 *
 * Handles:
 * - 2-letter abbreviations ("CA", "tx")
 * - Full state names ("California", "New York")
 * - FIPS codes as strings ("06", "36") or numbers (6, 36)
 *
 * Returns the abbreviation (upper-case) or `null` if unknown.
 */
export function normalizeToStateAbbr(value: unknown): string | null {
  if (value === null || value === undefined) {
    return null;
  }

  // Numeric FIPS
  if (typeof value === 'number') {
    const padded = String(Math.round(value)).padStart(2, '0');
    return FIPS_TO_STATE_ABBR[padded] ?? null;
  }

  if (typeof value !== 'string') {
    return null;
  }
  const trimmed = value.trim();
  if (!trimmed) {
    return null;
  }

  const upper = trimmed.toUpperCase();
  const lower = trimmed.toLowerCase();

  // 2-letter abbreviation
  if (upper.length === 2 && /^[A-Z]{2}$/.test(upper)) {
    // Validate it's a known state
    if (Object.values(FIPS_TO_STATE_ABBR).includes(upper)) {
      return upper;
    }
  }

  // Numeric FIPS as string (e.g. "06" or "6")
  if (/^\d{1,2}$/.test(trimmed)) {
    const padded = trimmed.padStart(2, '0');
    return FIPS_TO_STATE_ABBR[padded] ?? null;
  }

  // Full name lookup
  return STATE_NAME_TO_ABBR[lower] ?? null;
}

// ─── European country codes ────────────────────────────────────────────────

/**
 * ISO alpha-2 codes for European countries (UN members + common inclusions).
 * Used to filter `world-atlas` down to a Europe-only map.
 */
export const EUROPEAN_ALPHA2_CODES = new Set<string>([
  'AL',
  'AD',
  'AT',
  'BY',
  'BE',
  'BA',
  'BG',
  'HR',
  'CY',
  'CZ',
  'DK',
  'EE',
  'FI',
  'FR',
  'GE',
  'DE',
  'GR',
  'HU',
  'IS',
  'IE',
  'IT',
  'LV',
  'LI',
  'LT',
  'LU',
  'MT',
  'MD',
  'MC',
  'ME',
  'NL',
  'MK',
  'NO',
  'PL',
  'PT',
  'RO',
  'RU',
  'SM',
  'RS',
  'SK',
  'SI',
  'ES',
  'SE',
  'CH',
  'UA',
  'GB',
  'VA',
  'XK',
]);

// ─── Display-name helpers ─────────────────────────────────────────────────────

/** Cached Intl.DisplayNames instance for region (country) names. */
let regionDisplayNames: Intl.DisplayNames | null = null;

function getRegionDisplayNames(): Intl.DisplayNames | null {
  if (regionDisplayNames) {
    return regionDisplayNames;
  }
  try {
    // react-doctor-disable-next-line react-doctor/js-hoist-intl -- already lazy-cached at module scope
    regionDisplayNames = new Intl.DisplayNames(['en'], { type: 'region' });
    return regionDisplayNames;
  } catch {
    return null;
  }
}

/**
 * Returns the English display name for an ISO 3166-1 alpha-2 country code.
 * Uses `Intl.DisplayNames` for broad coverage; falls back to the raw code.
 */
export function alpha2ToName(code: string): string {
  try {
    return getRegionDisplayNames()?.of(code) ?? code;
  } catch {
    return code;
  }
}

/** Full US state name map (2-letter abbreviation → display name). */
export const STATE_ABBR_TO_NAME: Record<string, string> = {
  AL: 'Alabama',
  AK: 'Alaska',
  AZ: 'Arizona',
  AR: 'Arkansas',
  CA: 'California',
  CO: 'Colorado',
  CT: 'Connecticut',
  DE: 'Delaware',
  DC: 'District of Columbia',
  FL: 'Florida',
  GA: 'Georgia',
  HI: 'Hawaii',
  ID: 'Idaho',
  IL: 'Illinois',
  IN: 'Indiana',
  IA: 'Iowa',
  KS: 'Kansas',
  KY: 'Kentucky',
  LA: 'Louisiana',
  ME: 'Maine',
  MD: 'Maryland',
  MA: 'Massachusetts',
  MI: 'Michigan',
  MN: 'Minnesota',
  MS: 'Mississippi',
  MO: 'Missouri',
  MT: 'Montana',
  NE: 'Nebraska',
  NV: 'Nevada',
  NH: 'New Hampshire',
  NJ: 'New Jersey',
  NM: 'New Mexico',
  NY: 'New York',
  NC: 'North Carolina',
  ND: 'North Dakota',
  OH: 'Ohio',
  OK: 'Oklahoma',
  OR: 'Oregon',
  PA: 'Pennsylvania',
  RI: 'Rhode Island',
  SC: 'South Carolina',
  SD: 'South Dakota',
  TN: 'Tennessee',
  TX: 'Texas',
  UT: 'Utah',
  VT: 'Vermont',
  VA: 'Virginia',
  WA: 'Washington',
  WV: 'West Virginia',
  WI: 'Wisconsin',
  WY: 'Wyoming',
  AS: 'American Samoa',
  GU: 'Guam',
  MP: 'Northern Mariana Islands',
  PR: 'Puerto Rico',
  VI: 'U.S. Virgin Islands',
};
