/**
 * Redis-backed cache provider for @mui/x-studio-data-middleware.
 *
 * Implements `CacheProvider` using any Redis-compatible client.
 * Use this in multi-node or serverless deployments where `LRUCacheProvider`
 * (in-process only) would give each node an isolated cache.
 *
 * ## Supported clients
 *
 * This class accepts any object that conforms to the minimal `RedisClient`
 * interface below — it is compatible with both `ioredis` and `node-redis` (v4+)
 * without requiring either as a peer dependency.
 *
 * ### ioredis
 * ```ts
 * import Redis from 'ioredis';
 * import { RedisCacheProvider } from '@mui/x-studio-data-middleware';
 *
 * const redis = new Redis({ host: 'localhost', port: 6379 });
 * const cache = new RedisCacheProvider(redis);
 * ```
 *
 * ### node-redis (v4+)
 * ```ts
 * import { createClient } from 'redis';
 * import { RedisCacheProvider } from '@mui/x-studio-data-middleware';
 *
 * const redis = await createClient({ url: 'redis://localhost:6379' }).connect();
 * const cache = new RedisCacheProvider(redis);
 * ```
 *
 * ## TTL
 *
 * The default TTL is 60 seconds. Override per-call via the `opts.ttlMs` field
 * on `set()`, or set a default in the constructor options.
 *
 * ## Tag-based invalidation
 *
 * When `opts.tags` is provided to `set()`, two Redis SETs are maintained:
 *   - `__tag__:<tag>`  — forward index: maps tag → set of data keys
 *   - `__ktag__:<key>` — reverse index: maps data key → set of tags it belongs to
 *
 * `deleteByTag(tag)` evicts all matching entries in one round-trip.
 * `invalidatePrefix(prefix)` uses the reverse index to remove stale tag entries
 * for every key it deletes, keeping the forward index clean.
 *
 * Requires `sadd`, `smembers`, and `srem` on the Redis client (all three are
 * included in ioredis and node-redis v4+). If the client does not implement
 * them, both operations degrade gracefully (no tag cleanup, but no crash).
 *
 * ## Key format
 *
 * Cache keys are HMAC-scoped (generated by `generateCacheKey`) — they already
 * encode tenant and user context, so no additional namespacing is required
 * unless you share one Redis instance across multiple Studio deployments.
 * Use `keyPrefix` in the constructor options for that case.
 */

import type { CacheProvider, CacheEntry, CacheSetOpts } from './types';

export interface RedisClient {
  get(key: string): Promise<string | null>;
  set(key: string, value: string, exMode: 'EX', ttlSeconds: number): Promise<unknown>;
  keys(pattern: string): Promise<string[]>;
  del(...keys: string[]): Promise<unknown>;
  /** Optional — required for tag-based invalidation (ioredis + node-redis v4+ include this). */
  sadd?(key: string, ...members: string[]): Promise<unknown>;
  /** Optional — required for tag-based invalidation. */
  smembers?(key: string): Promise<string[]>;
  /** Optional — required for tag cleanup in invalidatePrefix when tags are in use. */
  srem?(key: string, ...members: string[]): Promise<unknown>;
}

export interface RedisCacheProviderOptions {
  /**
   * Default TTL in seconds for `set()` calls that don't specify one.
   * @default 60
   */
  defaultTtlSeconds?: number;
  /**
   * Optional key prefix applied to every Redis key.
   * Useful when sharing one Redis instance across multiple deployments.
   * @example 'studio:prod:'
   */
  keyPrefix?: string;
}

export class RedisCacheProvider implements CacheProvider {
  private readonly redis: RedisClient;
  private readonly defaultTtl: number;
  private readonly prefix: string;

  constructor(redis: RedisClient, options: RedisCacheProviderOptions = {}) {
    this.redis = redis;
    this.defaultTtl = options.defaultTtlSeconds ?? 60;
    this.prefix = options.keyPrefix ?? '';
  }

  async get(key: string): Promise<CacheEntry | undefined> {
    const raw = await this.redis.get(this.prefix + key);
    if (!raw) {
      return undefined;
    }
    try {
      return JSON.parse(raw) as CacheEntry;
    } catch {
      return undefined;
    }
  }

  async set(key: string, value: CacheEntry, opts?: CacheSetOpts): Promise<void> {
    const ttlSeconds = opts?.ttlMs !== undefined ? Math.ceil(opts.ttlMs / 1000) : this.defaultTtl;
    const prefixedKey = this.prefix + key;
    await this.redis.set(prefixedKey, JSON.stringify(value), 'EX', ttlSeconds);

    // Maintain forward (tag→keys) and reverse (key→tags) indexes for clean invalidation.
    const tags = opts?.tags;
    if (tags && tags.length > 0 && this.redis.sadd) {
      for (const tag of tags) {
        await this.redis.sadd(this.tagKey(tag), prefixedKey);
      }
      // Reverse index: lets invalidatePrefix remove stale forward-index entries
      await this.redis.sadd(this.keyTagsKey(prefixedKey), ...tags);
    }
  }

  async invalidatePrefix(prefix: string): Promise<void> {
    const pattern = `${this.prefix}${prefix}*`;
    const keys = await this.redis.keys(pattern);
    if (keys.length === 0) {
      return;
    }
    // Clean up tag indexes when supported, so forward index stays accurate.
    if (this.redis.smembers && this.redis.srem) {
      for (const key of keys) {
        const keyTagsKey = this.keyTagsKey(key);
        const tags = await this.redis.smembers(keyTagsKey);
        for (const tag of tags) {
          await this.redis.srem(this.tagKey(tag), key);
        }
      }
      await this.redis.del(...keys, ...keys.map((k) => this.keyTagsKey(k)));
    } else {
      await this.redis.del(...keys);
    }
  }

  async deleteByTag(tag: string): Promise<void> {
    // Graceful no-op when the Redis client doesn't support SET operations.
    if (!this.redis.smembers) {
      return;
    }
    const tagKey = this.tagKey(tag);
    const keys = await this.redis.smembers(tagKey);
    // Clean up the reverse index for each deleted key.
    if (keys.length > 0 && this.redis.srem) {
      for (const key of keys) {
        await this.redis.srem(this.keyTagsKey(key), tag);
      }
    }
    // Delete all tagged data keys plus the forward-index set itself.
    await this.redis.del(...keys, tagKey);
  }

  /** Redis key for the forward tag→keys index. */
  private tagKey(tag: string): string {
    return `${this.prefix}__tag__:${tag}`;
  }

  /** Redis key for the reverse key→tags index. */
  private keyTagsKey(key: string): string {
    return `__ktag__:${key}`;
  }
}
