/**
 * Redis-backed cache provider for @mui/x-studio-data-middleware.
 *
 * Implements `CacheProvider` using any Redis-compatible client.
 * Use this in multi-node or serverless deployments where `LRUCacheProvider`
 * (in-process only) would give each node an isolated cache.
 *
 * ## Supported clients
 *
 * This class accepts any object that conforms to the minimal `RedisClient`
 * interface below — it is compatible with both `ioredis` and `node-redis` (v4+)
 * without requiring either as a peer dependency. The two clients disagree on
 * two things this provider cares about, so the constructor detects which one
 * it was handed (or honors an explicit `clientStyle` option) and adapts:
 *
 *   - `SET key value EX seconds` — ioredis takes positional args
 *     (`set(key, value, 'EX', seconds)`); node-redis v4 takes an options object
 *     (`set(key, value, { EX: seconds })`). Calling the wrong shape against a
 *     real client either throws or silently sets a value with no TTL.
 *   - Set commands — ioredis exposes lowercase `sadd`/`smembers`/`srem`;
 *     node-redis v4 exposes camelCase `sAdd`/`sMembers`/`sRem`. Checking only
 *     the lowercase names (as earlier versions of this file did) means those
 *     checks are `undefined` on a real node-redis v4 client, so tag indexing
 *     and `deleteByTag` silently became no-ops — invalidation never happened
 *     and nothing told you.
 *
 * ### ioredis
 * ```ts
 * import Redis from 'ioredis';
 * import { RedisCacheProvider } from '@mui/x-studio-data-middleware';
 *
 * const redis = new Redis({ host: 'localhost', port: 6379 });
 * const cache = new RedisCacheProvider(redis);
 * ```
 *
 * ### node-redis (v4+)
 * ```ts
 * import { createClient } from 'redis';
 * import { RedisCacheProvider } from '@mui/x-studio-data-middleware';
 *
 * const redis = await createClient({ url: 'redis://localhost:6379' }).connect();
 * const cache = new RedisCacheProvider(redis);
 * ```
 *
 * ## TTL
 *
 * The default TTL is 60 seconds. Override per-call via the `opts.ttlMs` field
 * on `set()`, or set a default in the constructor options.
 *
 * ## Tag-based invalidation
 *
 * When `opts.tags` is provided to `set()`, two Redis SETs are maintained:
 *   - `__tag__:<tag>`  — forward index: maps tag → set of data keys
 *   - `__ktag__:<key>` — reverse index: maps data key → set of tags it belongs to
 *
 * Both index sets are given an expiry (refreshed on every write that touches
 * them, sized to the data key's own TTL) so that they don't outlive the data
 * keys they describe and grow Redis memory unboundedly.
 *
 * `deleteByTag(tag)` evicts all matching data keys, deletes each one's reverse
 * index (`__ktag__:<key>`) outright (it's meaningless once the data key is
 * gone), and deletes the forward index itself.
 * `invalidatePrefix(prefix)` uses the reverse index to remove stale tag entries
 * for every key it deletes, keeping the forward index clean, and scans for
 * matching keys via `SCAN` (never the blocking `KEYS` command), streaming one
 * cursor page at a time instead of materializing the whole matching key set.
 *
 * Both invalidation paths delete in FIXED-SIZE BATCHES (`DEL_BATCH_SIZE` in
 * `./redisCompat`). Spreading an unbounded key list into a single variadic
 * `del(...keys)` throws `RangeError: Maximum call stack size exceeded` past
 * V8's argument limit — before Redis is contacted at all — which
 * `handleMutation` swallows as a best-effort warning while still reporting the
 * write as `ok: true`, so the cache silently stops being invalidated exactly
 * when it holds the most entries.
 *
 * Requires `sAdd`/`sadd`, `sMembers`/`smembers`, and `sRem`/`srem` on the Redis
 * client (all are included in ioredis and node-redis v4+). If the client
 * implements neither naming convention, tag-based invalidation is unavailable;
 * this is logged once via `console.warn` rather than silently doing nothing.
 *
 * ## Key format
 *
 * Cache keys are HMAC-scoped (generated by `generateCacheKey`) — they already
 * encode tenant and user context, so no additional namespacing is required
 * unless you share one Redis instance across multiple Studio deployments.
 * Use `keyPrefix` in the constructor options for that case.
 */

import { isCacheEntryShape, type CacheProvider, type CacheEntry, type CacheSetOpts } from './types';
import { DEL_BATCH_SIZE, delKeys, scanKeyPages, setEx } from './redisCompat';

/**
 * Escape Redis glob metacharacters so a literal key prefix matches only itself in
 * a `SCAN MATCH` pattern.
 *
 * The tenant segment of a Studio cache key is `encodeURIComponent`-encoded
 * (`security/cacheKey.ts`), which neutralizes colons but NOT the Redis glob
 * metacharacters `*`, `?`, `[`, `]`, `^` and the escape char `\` (none are
 * percent-encoded). Interpolating an un-escaped tenant id like `ac*e` straight into
 * `SCAN MATCH studio:v1:ac*e*` would make the `*` a wildcard, so the eviction glob
 * also matches unrelated tenants (`ac`, `ace`, `acme`, …) → over-eviction (extra DB
 * load, never a cross-tenant read). Backslash-escaping each metacharacter keeps the
 * prefix a literal, so only the intended tenant's keys are scanned. The stored key
 * format is unchanged — this touches ONLY the SCAN pattern construction.
 */
export function escapeRedisGlob(literal: string): string {
  return literal.replace(/[*?[\]^\\]/g, (ch) => `\\${ch}`);
}

/**
 * Minimal structural interface compatible with both `ioredis` and `node-redis`
 * v4+. `set`/`sAdd`/`sadd`/etc. are typed loosely (rest args / `unknown`)
 * because the two client families disagree on exact call shapes — this
 * provider normalizes over that disagreement at runtime instead of in types.
 */
export interface RedisClient {
  get(key: string): Promise<string | null>;
  /**
   * Accepts either the ioredis positional form (`set(key, value, 'EX', seconds)`)
   * or the node-redis v4 options-object form (`set(key, value, { EX: seconds })`).
   */
  set(key: string, value: string, ...args: unknown[]): Promise<unknown>;
  del(...keys: string[]): Promise<unknown>;
  expire?(key: string, seconds: number): Promise<unknown>;
  /**
   * Remaining TTL of a key in seconds, Redis `TTL` semantics: `-2` if the key
   * doesn't exist, `-1` if it exists with no expiry, otherwise seconds
   * remaining. Optional — clients without it fall back to always extending
   * the tag index's expiry unconditionally (the pre-existing behavior).
   */
  ttl?(key: string): Promise<number>;
  /** Legacy O(N) key listing — only used as a last-resort fallback when `scan` is unavailable. */
  keys?(pattern: string): Promise<string[]>;
  /** Cursor-based key iteration. Preferred over `keys()` in production. */
  scan?(
    cursor: string,
    ...args: unknown[]
  ): Promise<[string, string[]] | { cursor: string | number; keys: string[] }>;
  /** ioredis-style SADD. */
  sadd?(key: string, ...members: string[]): Promise<unknown>;
  /** node-redis v4-style SADD. */
  sAdd?(key: string, members: string | string[]): Promise<unknown>;
  /** ioredis-style SMEMBERS. */
  smembers?(key: string): Promise<string[]>;
  /** node-redis v4-style SMEMBERS. */
  sMembers?(key: string): Promise<string[]>;
  /** ioredis-style SREM. */
  srem?(key: string, ...members: string[]): Promise<unknown>;
  /** node-redis v4-style SREM. */
  sRem?(key: string, members: string | string[]): Promise<unknown>;
}

export interface RedisCacheProviderOptions {
  /**
   * Default TTL in seconds for `set()` calls that don't specify one.
   * @default 60
   */
  defaultTtlSeconds?: number;
  /**
   * Optional key prefix applied to every Redis key.
   * Useful when sharing one Redis instance across multiple deployments.
   * @example 'studio:prod:'
   */
  keyPrefix?: string;
  /**
   * Force a specific client wire convention instead of auto-detecting it from
   * the shape of the injected client. Auto-detection checks for the presence
   * of camelCase `sAdd` (node-redis v4) vs lowercase `sadd` (ioredis).
   */
  clientStyle?: 'ioredis' | 'node-redis';
  /** Number of keys requested per SCAN iteration. @default 1000 */
  scanCount?: number;
}

/**
 * Detects which client naming convention `redis` implements.
 * Exported so `RedisTierCacheProvider` (which shares the same `RedisClient`
 * duck-typed interface) can reuse the same detection instead of duplicating it.
 */
export function detectClientStyle(redis: RedisClient): 'ioredis' | 'node-redis' {
  if (typeof redis.sAdd === 'function') {
    return 'node-redis';
  }
  return 'ioredis';
}

export class RedisCacheProvider implements CacheProvider {
  private readonly redis: RedisClient;

  private readonly defaultTtl: number;

  private readonly prefix: string;

  private readonly clientStyle: 'ioredis' | 'node-redis';

  private readonly scanCount: number;

  private warnedTagsUnavailable = false;

  private warnedMalformedEntry = false;

  constructor(redis: RedisClient, options: RedisCacheProviderOptions = {}) {
    this.redis = redis;
    this.defaultTtl = options.defaultTtlSeconds ?? 60;
    this.prefix = options.keyPrefix ?? '';
    this.clientStyle = options.clientStyle ?? detectClientStyle(redis);
    this.scanCount = options.scanCount ?? 1000;
  }

  async get(key: string): Promise<CacheEntry | undefined> {
    const raw = await this.redis.get(this.prefix + key);
    if (!raw) {
      return undefined;
    }
    let parsed: unknown;
    try {
      parsed = JSON.parse(raw);
    } catch {
      return undefined;
    }
    // Validate the SHAPE, not just the JSON-ness (see `isCacheEntryShape`): a
    // foreign value stored under a colliding key parses fine and would
    // otherwise be served as a result set.
    if (!isCacheEntryShape(parsed)) {
      this.warnMalformedEntry(key);
      return undefined;
    }
    return parsed;
  }

  async set(key: string, value: CacheEntry, opts?: CacheSetOpts): Promise<void> {
    const ttlSeconds = opts?.ttlMs !== undefined ? Math.ceil(opts.ttlMs / 1000) : this.defaultTtl;
    const prefixedKey = this.prefix + key;
    await this.redisSetEx(prefixedKey, JSON.stringify(value), Math.max(1, ttlSeconds));

    // Maintain forward (tag→keys) and reverse (key→tags) indexes for clean invalidation.
    const tags = opts?.tags;
    if (tags && tags.length > 0) {
      const supported = await this.sAdd(this.keyTagsKey(prefixedKey), tags);
      if (supported) {
        for (const tag of tags) {
          // eslint-disable-next-line no-await-in-loop
          await this.sAdd(this.tagKey(tag), [prefixedKey]);
          // eslint-disable-next-line no-await-in-loop
          await this.extendTagIndexExpiry(this.tagKey(tag), Math.max(1, ttlSeconds));
        }
        // Reverse index TTL mirrors the data key's own TTL — it's meaningless
        // once the data key it describes has expired.
        await this.expire(this.keyTagsKey(prefixedKey), Math.max(1, ttlSeconds));
      }
    }
  }

  async invalidatePrefix(prefix: string): Promise<void> {
    // Escape glob metacharacters in the LITERAL prefix portion (host key prefix +
    // caller-supplied tenant prefix) so only the trailing `*` acts as a wildcard —
    // a tenant id containing `*`/`?`/`[`/`]` must not widen the eviction glob to
    // unrelated tenants (over-eviction). The stored keys keep their raw format;
    // only this match pattern is escaped.
    const pattern = `${escapeRedisGlob(this.prefix)}${escapeRedisGlob(prefix)}*`;
    const tagsSupported = await this.tagOpsSupported();
    // Stream one SCAN page at a time and delete incrementally, rather than
    // accumulating every matching key into one array and spreading it into a
    // single `del(...keys)` (finding M1). A tenant's keyspace is unbounded, so
    // the accumulating form was both a memory spike proportional to the
    // keyspace and — past V8's spread-argument limit — a `RangeError` thrown
    // before Redis was ever contacted, i.e. an invalidation that silently
    // deleted nothing. Deleting while the cursor is open is safe: SCAN
    // guarantees every key present for the whole iteration is returned.
    for await (const page of scanKeyPages(this.redis, this.clientStyle, pattern, this.scanCount)) {
      // Clean up tag indexes when supported, so the forward index stays accurate.
      if (tagsSupported) {
        for (const key of page) {
          const keyTagsKey = this.keyTagsKey(key);
          // eslint-disable-next-line no-await-in-loop
          const tags = await this.sMembers(keyTagsKey);
          for (const tag of tags) {
            // eslint-disable-next-line no-await-in-loop
            await this.sRem(this.tagKey(tag), [key]);
          }
        }

        await delKeys(this.redis, [...page, ...page.map((k) => this.keyTagsKey(k))]);
      } else {
        await delKeys(this.redis, page);
      }
    }
  }

  async deleteByTag(tag: string): Promise<void> {
    if (!(await this.tagOpsSupported())) {
      // Loudly note that tag-based invalidation cannot run, instead of a
      // silent no-op — the caller thinks the cache was invalidated.
      this.warnTagsUnavailable();
      return;
    }
    const tagKey = this.tagKey(tag);
    const keys = await this.sMembers(tagKey);
    if (keys.length === 0) {
      return;
    }
    // Delete every tagged data key, its now-meaningless reverse-index entry, and
    // the forward-index set itself — in FIXED-SIZE BATCHES (finding M1), never
    // one variadic `del(...keys)` spread. The forward index accumulates one
    // member per (tenant × security profile × query shape) within its TTL, so a
    // single-call spread hit V8's argument limit and threw `RangeError` before
    // reaching Redis; `handleMutation` then logged that as a best-effort warning
    // and still reported `ok: true`, leaving every read stale for the full TTL.
    // `tagKey` goes last so the forward index outlives its members: a failure
    // mid-drain leaves the index pointing at already-deleted keys, which a retry
    // simply re-deletes (safe), rather than orphaning live keys with no index.
    const ktagKeys = keys.map((key) => this.keyTagsKey(key));
    await delKeys(this.redis, [...keys, ...ktagKeys, tagKey]);
  }

  /** Redis key for the forward tag→keys index. */
  private tagKey(tag: string): string {
    return `${this.prefix}__tag__:${tag}`;
  }

  /** Redis key for the reverse key→tags index. */
  private keyTagsKey(key: string): string {
    return `${this.prefix}__ktag__:${key}`;
  }

  /** `SET key value EX seconds`, adapted to the detected client convention. */
  private async redisSetEx(key: string, value: string, ttlSeconds: number): Promise<void> {
    await setEx(this.redis, this.clientStyle, key, value, ttlSeconds);
  }

  /** Whether this client exposes set operations under either naming convention. */
  private async tagOpsSupported(): Promise<boolean> {
    return Boolean(
      (typeof this.redis.sAdd === 'function' || typeof this.redis.sadd === 'function') &&
      (typeof this.redis.sMembers === 'function' || typeof this.redis.smembers === 'function'),
    );
  }

  /**
   * Normalized SADD — returns false (and does nothing) if unsupported.
   *
   * Members are added in fixed-size batches for the same reason `delKeys`
   * batches (finding M1, sibling site): the ioredis arm spreads them into a
   * variadic call, which has an engine argument ceiling. `tags` is host-supplied
   * and small in practice, but "small in practice" is what made the `del`
   * spread a latent failure rather than an obvious one.
   */
  private async sAdd(key: string, members: string[]): Promise<boolean> {
    if (typeof this.redis.sAdd !== 'function' && typeof this.redis.sadd !== 'function') {
      this.warnTagsUnavailable();
      return false;
    }
    for (let i = 0; i < members.length; i += DEL_BATCH_SIZE) {
      const chunk = members.slice(i, i + DEL_BATCH_SIZE);
      if (typeof this.redis.sAdd === 'function') {
        // eslint-disable-next-line no-await-in-loop
        await this.redis.sAdd(key, chunk);
      } else if (typeof this.redis.sadd === 'function') {
        // eslint-disable-next-line no-await-in-loop
        await this.redis.sadd(key, ...chunk);
      }
    }
    return true;
  }

  /** Normalized SMEMBERS — returns `[]` if unsupported. */
  private async sMembers(key: string): Promise<string[]> {
    if (typeof this.redis.sMembers === 'function') {
      return this.redis.sMembers(key);
    }
    if (typeof this.redis.smembers === 'function') {
      return this.redis.smembers(key);
    }
    this.warnTagsUnavailable();
    return [];
  }

  /** Normalized SREM — no-op if unsupported. */
  private async sRem(key: string, members: string[]): Promise<void> {
    if (typeof this.redis.sRem === 'function') {
      await this.redis.sRem(key, members);
    } else if (typeof this.redis.srem === 'function') {
      await this.redis.srem(key, ...members);
    } else {
      this.warnTagsUnavailable();
    }
  }

  /** Refresh a key's expiry; no-op if the client doesn't implement EXPIRE. */
  private async expire(key: string, seconds: number): Promise<void> {
    if (typeof this.redis.expire === 'function') {
      await this.redis.expire(key, seconds);
    }
  }

  /**
   * Extend the forward tag index's (`__tag__:<tag>`) expiry, but never shorten
   * it (finding 1.9). The index is shared across every entry tagged with
   * `tag`; if entry A is written with a long TTL and entry B (same tag) is
   * later written with a short TTL, unconditionally resetting the index's
   * expiry to B's TTL would let the index expire out from under A while A is
   * still live — silently breaking `deleteByTag` for A.
   *
   * When the client supports `TTL`, only call `EXPIRE` if doing so would
   * actually extend the index's remaining life. When it doesn't, fall back to
   * the previous unconditional-extend behavior (best effort).
   */
  private async extendTagIndexExpiry(tagKey: string, ttlSeconds: number): Promise<void> {
    if (typeof this.redis.ttl === 'function') {
      const remaining = await this.redis.ttl(tagKey);
      // remaining >= 0 means the key exists with an active expiry. If it
      // already outlives the new entry's TTL, leave it alone.
      if (remaining >= 0 && remaining >= ttlSeconds) {
        return;
      }
    }
    await this.expire(tagKey, ttlSeconds);
  }

  private warnTagsUnavailable(): void {
    if (this.warnedTagsUnavailable) {
      return;
    }
    this.warnedTagsUnavailable = true;
    console.warn(
      'MUI X Studio Server: the Redis client passed to RedisCacheProvider implements neither ' +
        'sAdd/sMembers/sRem (node-redis v4+) nor sadd/smembers/srem (ioredis). ' +
        'Tag-based cache invalidation (deleteByTag) cannot run and is being skipped — ' +
        'stale cached rows may be served after a mutation. Provide a client that implements ' +
        'one of these method sets to enable table-level cache invalidation.',
    );
  }

  /**
   * Warn (once per provider instance) that a stored value parsed as JSON but is
   * not a `CacheEntry`. Once-only because the usual cause — a keyspace collision
   * with the host's own Redis keys — recurs on every read of that key and would
   * otherwise flood the logs.
   */
  private warnMalformedEntry(key: string): void {
    if (this.warnedMalformedEntry) {
      return;
    }
    this.warnedMalformedEntry = true;
    console.warn(
      `MUI X Studio Server: the value stored in Redis under cache key "${this.prefix}${key}" parsed as JSON but ` +
        'is not a CacheEntry (it needs a "rows" array, and — when present — a "tier" of client/server/db and a ' +
        'finite numeric "rowCount"). It is being treated as a cache MISS so the query re-reads from the ' +
        'database rather than serving a foreign value as a result set. This usually means another writer shares ' +
        "this Redis keyspace — set a distinct `keyPrefix` in RedisCacheProvider's options to namespace Studio's keys.",
    );
  }
}
