import type { StudioDataSource } from '@mui/x-studio';

export const CUSTOMERS_SOURCE_ID = 'source-customers';

export const customersSource: StudioDataSource = {
  id: CUSTOMERS_SOURCE_ID,
  label: 'Sales Customers',
  tableName: 'customers',
  fields: [
    { id: 'id', label: 'Customer ID', type: 'string', hidden: true },
    { id: 'company', label: 'Company', type: 'string' },
    { id: 'contact', label: 'Contact Name', type: 'string' },
    { id: 'email', label: 'Email', type: 'string' },
    { id: 'country', label: 'Country', type: 'string' },
    { id: 'segment', label: 'Segment', type: 'string' },
    { id: 'since', label: 'Customer Since', type: 'date' },
  ],
  rows: [
    {
      id: 'CUS-001',
      company: 'TechCorp GmbH',
      contact: 'Hans Mueller',
      email: 'h.mueller@techcorp.de',
      country: 'Germany',
      segment: 'Enterprise',
      since: '2019-03-15',
    },
    {
      id: 'CUS-002',
      company: 'Berlin Digital AG',
      contact: 'Petra Schneider',
      email: 'p.schneider@berlindigital.de',
      country: 'Germany',
      segment: 'Mid-Market',
      since: '2020-06-10',
    },
    {
      id: 'CUS-003',
      company: 'Munich Systems GmbH',
      contact: 'Klaus Weber',
      email: 'k.weber@munichsys.de',
      country: 'Germany',
      segment: 'Enterprise',
      since: '2018-09-22',
    },
    {
      id: 'CUS-004',
      company: 'Hamburg Tech',
      contact: 'Sabine Fischer',
      email: 's.fischer@hamburgtech.de',
      country: 'Germany',
      segment: 'SMB',
      since: '2021-02-14',
    },
    {
      id: 'CUS-005',
      company: 'Frankfurt Solutions',
      contact: 'Michael Bauer',
      email: 'm.bauer@frankfurtsol.de',
      country: 'Germany',
      segment: 'Mid-Market',
      since: '2022-01-08',
    },
    {
      id: 'CUS-006',
      company: 'London Digital Ltd',
      contact: 'Sarah Thompson',
      email: 's.thompson@londondigital.co.uk',
      country: 'UK',
      segment: 'Enterprise',
      since: '2018-11-08',
    },
    {
      id: 'CUS-007',
      company: 'Manchester Tech PLC',
      contact: 'James Wilson',
      email: 'j.wilson@manchestertech.co.uk',
      country: 'UK',
      segment: 'Enterprise',
      since: '2019-04-17',
    },
    {
      id: 'CUS-008',
      company: 'Edinburgh Software',
      contact: 'Fiona Campbell',
      email: 'f.campbell@edinburghsw.co.uk',
      country: 'UK',
      segment: 'Mid-Market',
      since: '2020-08-25',
    },
    {
      id: 'CUS-009',
      company: 'Bristol Innovations',
      contact: 'David Brown',
      email: 'd.brown@bristolinno.co.uk',
      country: 'UK',
      segment: 'SMB',
      since: '2021-05-30',
    },
    {
      id: 'CUS-010',
      company: 'Leeds Data Services',
      contact: 'Emma Taylor',
      email: 'e.taylor@leedsdata.co.uk',
      country: 'UK',
      segment: 'Mid-Market',
      since: '2022-03-12',
    },
    {
      id: 'CUS-011',
      company: 'Paris Tech SARL',
      contact: 'Marie Dubois',
      email: 'marie.dubois@paristech.fr',
      country: 'France',
      segment: 'Mid-Market',
      since: '2019-07-22',
    },
    {
      id: 'CUS-012',
      company: 'Lyon Digital',
      contact: 'Pierre Martin',
      email: 'p.martin@lyondigital.fr',
      country: 'France',
      segment: 'Enterprise',
      since: '2020-01-15',
    },
    {
      id: 'CUS-013',
      company: 'Marseille Systems',
      contact: 'Sophie Bernard',
      email: 's.bernard@marseillesys.fr',
      country: 'France',
      segment: 'SMB',
      since: '2021-09-03',
    },
    {
      id: 'CUS-014',
      company: 'Toulouse Innovations',
      contact: 'Jean Leroy',
      email: 'j.leroy@toulouseinno.fr',
      country: 'France',
      segment: 'Mid-Market',
      since: '2022-04-28',
    },
    {
      id: 'CUS-015',
      company: 'New York Systems Inc',
      contact: 'John Smith',
      email: 'j.smith@nysystems.com',
      country: 'USA',
      segment: 'Enterprise',
      since: '2018-05-10',
    },
    {
      id: 'CUS-016',
      company: 'San Francisco Tech',
      contact: 'Lisa Chen',
      email: 'l.chen@sftech.com',
      country: 'USA',
      segment: 'Enterprise',
      since: '2019-11-20',
    },
    {
      id: 'CUS-017',
      company: 'Chicago Digital LLC',
      contact: 'Robert Johnson',
      email: 'r.johnson@chicagodigital.com',
      country: 'USA',
      segment: 'Mid-Market',
      since: '2020-03-08',
    },
    {
      id: 'CUS-018',
      company: 'Austin Innovations',
      contact: 'Jennifer Davis',
      email: 'j.davis@austininno.com',
      country: 'USA',
      segment: 'SMB',
      since: '2021-07-14',
    },
    {
      id: 'CUS-019',
      company: 'Toronto Tech Corp',
      contact: 'Michael Lee',
      email: 'm.lee@torontotech.ca',
      country: 'Canada',
      segment: 'Enterprise',
      since: '2019-02-28',
    },
    {
      id: 'CUS-020',
      company: 'Vancouver Digital',
      contact: 'Emily Wong',
      email: 'e.wong@vancouverdigital.ca',
      country: 'Canada',
      segment: 'Mid-Market',
      since: '2020-10-05',
    },
    {
      id: 'CUS-021',
      company: 'Montreal Systems',
      contact: 'François Tremblay',
      email: 'f.tremblay@montrealsys.ca',
      country: 'Canada',
      segment: 'SMB',
      since: '2022-06-18',
    },
    {
      id: 'CUS-022',
      company: 'Madrid Tech S.L.',
      contact: 'Isabel Rodriguez',
      email: 'i.rodriguez@madridtech.es',
      country: 'Spain',
      segment: 'Enterprise',
      since: '2019-05-15',
    },
    {
      id: 'CUS-023',
      company: 'Barcelona Digital',
      contact: 'Carlos Fernandez',
      email: 'c.fernandez@bcndigital.es',
      country: 'Spain',
      segment: 'Mid-Market',
      since: '2020-08-20',
    },
    {
      id: 'CUS-024',
      company: 'Valencia Systems',
      contact: 'Ana Lopez',
      email: 'a.lopez@valenciasys.es',
      country: 'Spain',
      segment: 'SMB',
      since: '2021-11-10',
    },
    {
      id: 'CUS-025',
      company: 'Seville Solutions',
      contact: 'Miguel Sanchez',
      email: 'm.sanchez@sevillesol.es',
      country: 'Spain',
      segment: 'Mid-Market',
      since: '2022-03-25',
    },
    {
      id: 'CUS-026',
      company: 'Amsterdam Digital BV',
      contact: 'Pieter van der Berg',
      email: 'p.vanderberg@amstdigital.nl',
      country: 'Netherlands',
      segment: 'Enterprise',
      since: '2019-01-20',
    },
    {
      id: 'CUS-027',
      company: 'Rotterdam Tech',
      contact: 'Jan de Vries',
      email: 'j.devries@rotterdamtech.nl',
      country: 'Netherlands',
      segment: 'Mid-Market',
      since: '2020-05-15',
    },
    {
      id: 'CUS-028',
      company: 'Utrecht Systems',
      contact: 'Maria Bakker',
      email: 'm.bakker@utrechtsys.nl',
      country: 'Netherlands',
      segment: 'SMB',
      since: '2021-09-08',
    },
    {
      id: 'CUS-029',
      company: 'Stockholm Digital AB',
      contact: 'Erik Lindqvist',
      email: 'e.lindqvist@stockdigital.se',
      country: 'Sweden',
      segment: 'Enterprise',
      since: '2019-04-12',
    },
    {
      id: 'CUS-030',
      company: 'Gothenburg Tech',
      contact: 'Anna Svensson',
      email: 'a.svensson@gbgtech.se',
      country: 'Sweden',
      segment: 'Mid-Market',
      since: '2020-11-03',
    },
    {
      id: 'CUS-031',
      company: 'Malmo Systems',
      contact: 'Lars Johansson',
      email: 'l.johansson@malmosys.se',
      country: 'Sweden',
      segment: 'SMB',
      since: '2022-02-28',
    },
    {
      id: 'CUS-032',
      company: 'Warsaw Digital Sp. z o.o.',
      contact: 'Pawel Kowalski',
      email: 'p.kowalski@wawdigital.pl',
      country: 'Poland',
      segment: 'Enterprise',
      since: '2020-03-10',
    },
    {
      id: 'CUS-033',
      company: 'Krakow Tech',
      contact: 'Marta Nowak',
      email: 'm.nowak@krktech.pl',
      country: 'Poland',
      segment: 'Mid-Market',
      since: '2021-07-22',
    },
    {
      id: 'CUS-034',
      company: 'Wroclaw Systems',
      contact: 'Tomasz Wisniewski',
      email: 't.wisniewski@wrcsys.pl',
      country: 'Poland',
      segment: 'SMB',
      since: '2022-08-15',
    },
    {
      id: 'CUS-035',
      company: 'Calgary Digital',
      contact: 'Sophie Martin',
      email: 's.martin@calgarydigital.ca',
      country: 'Canada',
      segment: 'Mid-Market',
      since: '2020-04-18',
    },
    {
      id: 'CUS-036',
      company: 'Ottawa Tech Corp',
      contact: 'David Wilson',
      email: 'd.wilson@ottawatech.ca',
      country: 'Canada',
      segment: 'Enterprise',
      since: '2019-09-05',
    },
    {
      id: 'CUS-037',
      company: 'Edmonton Systems',
      contact: 'Jennifer Chen',
      email: 'j.chen@edmontonsys.ca',
      country: 'Canada',
      segment: 'SMB',
      since: '2021-12-01',
    },
    {
      id: 'CUS-038',
      company: 'Winnipeg Digital',
      contact: 'Michael Brown',
      email: 'm.brown@winnipegdigital.ca',
      country: 'Canada',
      segment: 'Mid-Market',
      since: '2022-05-14',
    },
    {
      id: 'CUS-039',
      company: 'Sydney Digital Pty Ltd',
      contact: 'James Anderson',
      email: 'j.anderson@sydneydigital.com.au',
      country: 'Australia',
      segment: 'Enterprise',
      since: '2019-06-20',
    },
    {
      id: 'CUS-040',
      company: 'Melbourne Tech',
      contact: 'Sarah Davis',
      email: 's.davis@melbtech.com.au',
      country: 'Australia',
      segment: 'Enterprise',
      since: '2020-02-15',
    },
    {
      id: 'CUS-041',
      company: 'Brisbane Systems',
      contact: 'Robert Taylor',
      email: 'r.taylor@brissystems.com.au',
      country: 'Australia',
      segment: 'Mid-Market',
      since: '2021-04-08',
    },
    {
      id: 'CUS-042',
      company: 'Perth Digital',
      contact: 'Emily Johnson',
      email: 'e.johnson@perthdigital.com.au',
      country: 'Australia',
      segment: 'SMB',
      since: '2022-07-19',
    },
    {
      id: 'CUS-043',
      company: 'Seattle Tech Inc',
      contact: 'William Martinez',
      email: 'w.martinez@seattletech.com',
      country: 'USA',
      segment: 'Enterprise',
      since: '2019-08-14',
    },
    {
      id: 'CUS-044',
      company: 'Boston Digital',
      contact: 'Amanda White',
      email: 'a.white@bostondigital.com',
      country: 'USA',
      segment: 'Mid-Market',
      since: '2020-06-25',
    },
    {
      id: 'CUS-045',
      company: 'Miami Systems',
      contact: 'Christopher Lee',
      email: 'c.lee@miamisystems.com',
      country: 'USA',
      segment: 'SMB',
      since: '2021-03-17',
    },
    {
      id: 'CUS-046',
      company: 'Denver Innovations',
      contact: 'Patricia Harris',
      email: 'p.harris@denveriinno.com',
      country: 'USA',
      segment: 'Mid-Market',
      since: '2022-09-30',
    },
    {
      id: 'CUS-047',
      company: 'Birmingham Tech Ltd',
      contact: 'Andrew Thompson',
      email: 'a.thompson@birminghamtech.co.uk',
      country: 'UK',
      segment: 'Enterprise',
      since: '2019-10-22',
    },
    {
      id: 'CUS-048',
      company: 'Glasgow Digital',
      contact: 'Karen Wilson',
      email: 'k.wilson@glasgowdigital.co.uk',
      country: 'UK',
      segment: 'Mid-Market',
      since: '2020-07-18',
    },
    {
      id: 'CUS-049',
      company: 'Liverpool Systems',
      contact: 'Thomas Evans',
      email: 't.evans@liverpoolsys.co.uk',
      country: 'UK',
      segment: 'SMB',
      since: '2021-06-05',
    },
    {
      id: 'CUS-050',
      company: 'Cardiff Innovations',
      contact: 'Rebecca Jones',
      email: 'r.jones@cardiffinno.co.uk',
      country: 'UK',
      segment: 'Mid-Market',
      since: '2022-11-28',
    },
  ],
};
