import type { StudioDataSource } from '@mui/x-studio';
import { CATEGORY_REVENUE_MULTIPLIERS, roundCurrency } from './categoryRevenueMultipliers';

export const PRODUCTS_SOURCE_ID = 'source-products';

function boostProductCategoryRevenue(rows: StudioDataSource['rows']): StudioDataSource['rows'] {
  return rows.map((row) => {
    const multiplier = CATEGORY_REVENUE_MULTIPLIERS[String(row.category)] ?? 1;
    if (multiplier === 1) {
      return row;
    }

    return {
      ...row,
      price: roundCurrency(Number(row.price ?? 0) * multiplier),
    };
  });
}

export const productsSource: StudioDataSource = {
  id: PRODUCTS_SOURCE_ID,
  label: 'Products',
  tableName: 'products',
  fields: [
    { id: 'id', label: 'Product ID', type: 'string', hidden: true },
    { id: 'product', label: 'Product', type: 'string' },
    { id: 'category', label: 'Category', type: 'string' },
    { id: 'price', label: 'Unit Price', type: 'number', format: 'currency' },
    { id: 'cost', label: 'Unit Cost', type: 'number', format: 'currency' },
    { id: 'stock', label: 'In Stock', type: 'number', format: 'integer' },
    { id: 'reorderLevel', label: 'Reorder Level', type: 'number', format: 'integer' },
  ],
  rows: boostProductCategoryRevenue([
    {
      id: 'PRD-001',
      product: 'Laptop Pro 15"',
      category: 'Electronics',
      price: 1299,
      cost: 850,
      stock: 45,
      reorderLevel: 20,
    },
    {
      id: 'PRD-002',
      product: 'Wireless Mouse',
      category: 'Electronics',
      price: 49,
      cost: 18,
      stock: 230,
      reorderLevel: 50,
    },
    {
      id: 'PRD-003',
      product: 'USB-C Hub',
      category: 'Electronics',
      price: 79,
      cost: 32,
      stock: 156,
      reorderLevel: 40,
    },
    {
      id: 'PRD-004',
      product: 'Mechanical Keyboard',
      category: 'Electronics',
      price: 149,
      cost: 65,
      stock: 88,
      reorderLevel: 30,
    },
    {
      id: 'PRD-005',
      product: 'Monitor 27" 4K',
      category: 'Electronics',
      price: 449,
      cost: 280,
      stock: 34,
      reorderLevel: 15,
    },
    {
      id: 'PRD-006',
      product: 'Office Chair Ergonomic',
      category: 'Furniture',
      price: 399,
      cost: 180,
      stock: 22,
      reorderLevel: 10,
    },
    {
      id: 'PRD-007',
      product: 'Standing Desk',
      category: 'Furniture',
      price: 599,
      cost: 320,
      stock: 18,
      reorderLevel: 8,
    },
    {
      id: 'PRD-008',
      product: 'Desk Lamp LED',
      category: 'Furniture',
      price: 69,
      cost: 25,
      stock: 95,
      reorderLevel: 25,
    },
    {
      id: 'PRD-009',
      product: 'Webcam HD',
      category: 'Electronics',
      price: 89,
      cost: 38,
      stock: 142,
      reorderLevel: 35,
    },
    {
      id: 'PRD-010',
      product: 'Headphones Noise-Cancel',
      category: 'Electronics',
      price: 299,
      cost: 145,
      stock: 67,
      reorderLevel: 20,
    },
    {
      id: 'PRD-011',
      product: 'Printer Laser',
      category: 'Electronics',
      price: 349,
      cost: 210,
      stock: 28,
      reorderLevel: 12,
    },
    {
      id: 'PRD-012',
      product: 'Paper A4 (500 sheets)',
      category: 'Supplies',
      price: 12,
      cost: 6,
      stock: 520,
      reorderLevel: 100,
    },
    {
      id: 'PRD-013',
      product: 'Ink Cartridge Black',
      category: 'Supplies',
      price: 35,
      cost: 12,
      stock: 180,
      reorderLevel: 40,
    },
    {
      id: 'PRD-014',
      product: 'Ink Cartridge Color',
      category: 'Supplies',
      price: 45,
      cost: 16,
      stock: 145,
      reorderLevel: 35,
    },
    {
      id: 'PRD-015',
      product: 'Notebook Set (3-pack)',
      category: 'Supplies',
      price: 18,
      cost: 7,
      stock: 340,
      reorderLevel: 80,
    },
    {
      id: 'PRD-016',
      product: 'Whiteboard 48x36"',
      category: 'Furniture',
      price: 129,
      cost: 55,
      stock: 15,
      reorderLevel: 8,
    },
    {
      id: 'PRD-017',
      product: 'Filing Cabinet',
      category: 'Furniture',
      price: 249,
      cost: 120,
      stock: 12,
      reorderLevel: 6,
    },
    {
      id: 'PRD-018',
      product: 'External SSD 1TB',
      category: 'Electronics',
      price: 119,
      cost: 65,
      stock: 78,
      reorderLevel: 25,
    },
    {
      id: 'PRD-019',
      product: 'Tablet 10"',
      category: 'Electronics',
      price: 449,
      cost: 290,
      stock: 42,
      reorderLevel: 15,
    },
    {
      id: 'PRD-020',
      product: 'Docking Station',
      category: 'Electronics',
      price: 199,
      cost: 95,
      stock: 56,
      reorderLevel: 20,
    },
    {
      id: 'PRD-021',
      product: 'Cloud Storage 1TB (Annual)',
      category: 'Software',
      price: 99,
      cost: 15,
      stock: 999,
      reorderLevel: 100,
    },
    {
      id: 'PRD-022',
      product: 'Antivirus Suite (1-year)',
      category: 'Software',
      price: 49,
      cost: 8,
      stock: 999,
      reorderLevel: 100,
    },
    {
      id: 'PRD-023',
      product: 'Project Management Tool',
      category: 'Software',
      price: 199,
      cost: 38,
      stock: 999,
      reorderLevel: 50,
    },
    {
      id: 'PRD-024',
      product: 'VPN Service (Annual)',
      category: 'Software',
      price: 79,
      cost: 12,
      stock: 999,
      reorderLevel: 100,
    },
    {
      id: 'PRD-025',
      product: 'Office Suite License',
      category: 'Software',
      price: 299,
      cost: 60,
      stock: 999,
      reorderLevel: 50,
    },
    {
      id: 'PRD-026',
      product: 'IT Support - Basic (annual)',
      category: 'Services',
      price: 599,
      cost: 150,
      stock: 200,
      reorderLevel: 20,
    },
    {
      id: 'PRD-027',
      product: 'IT Support - Premium (annual)',
      category: 'Services',
      price: 1499,
      cost: 400,
      stock: 50,
      reorderLevel: 5,
    },
    {
      id: 'PRD-028',
      product: 'Network Setup Service',
      category: 'Services',
      price: 899,
      cost: 250,
      stock: 30,
      reorderLevel: 5,
    },
    {
      id: 'PRD-029',
      product: 'Data Backup Service (annual)',
      category: 'Services',
      price: 249,
      cost: 60,
      stock: 150,
      reorderLevel: 15,
    },
    {
      id: 'PRD-030',
      product: 'Cloud Migration Package',
      category: 'Services',
      price: 2499,
      cost: 700,
      stock: 20,
      reorderLevel: 3,
    },
    {
      id: 'PRD-031',
      product: 'Network Switch 24-Port',
      category: 'Networking',
      price: 249,
      cost: 110,
      stock: 45,
      reorderLevel: 15,
    },
    {
      id: 'PRD-032',
      product: 'WiFi Router Enterprise',
      category: 'Networking',
      price: 349,
      cost: 160,
      stock: 30,
      reorderLevel: 10,
    },
    {
      id: 'PRD-033',
      product: 'Ethernet Cable Cat6 (100m)',
      category: 'Networking',
      price: 39,
      cost: 12,
      stock: 200,
      reorderLevel: 50,
    },
    {
      id: 'PRD-034',
      product: 'Patch Panel 24-Port',
      category: 'Networking',
      price: 129,
      cost: 55,
      stock: 25,
      reorderLevel: 8,
    },
    {
      id: 'PRD-035',
      product: 'Network Rack 12U',
      category: 'Networking',
      price: 349,
      cost: 140,
      stock: 15,
      reorderLevel: 5,
    },
  ]),
};
