import type { StudioState } from '@mui/x-studio';
import {
  OS_STORES_SOURCE_ID,
  OS_PRODUCTS_SOURCE_ID,
  OS_CUSTOMERS_SOURCE_ID,
  OS_ORDERS_SOURCE_ID,
  OS_ORDER_ITEMS_SOURCE_ID,
  OS_SHIPMENTS_SOURCE_ID,
} from '../officeSuppliesData';

type OfficeSuppliesWidgetConfig = StudioState['widgets'][string]['config'] & {
  xFieldSourceId?: string;
  seriesFieldSourceId?: string;
  filters?: Array<{
    fieldId: string;
    operator: 'equals';
    value: boolean;
  }>;
};

const widgetConfig = (config: OfficeSuppliesWidgetConfig) => config;

export const OS_INITIAL_STATE: Partial<StudioState> = {
  dashboard: {
    id: 'dashboard-os',
    title: 'Office Supplies Dashboard',
    activePageId: 'os-page-1',
  },
  pages: {
    'os-page-1': {
      id: 'os-page-1',
      title: 'Executive Overview',
      widgetRows: [
        ['os-text-hero'],
        ['os-kpi-revenue', 'os-kpi-orders', 'os-kpi-customers', 'os-kpi-gm-pct'],
        ['os-chart-revenue-trend'],
        ['os-chart-revenue-by-category', 'os-chart-revenue-by-region'],
        ['os-grid-orders'],
      ],
    },
    'os-page-2': {
      id: 'os-page-2',
      title: 'Sales & Margin',
      widgetRows: [
        ['os-text-sales'],
        ['os-filter-category'],
        ['os-chart-revenue-by-brand', 'os-chart-gm-by-subcategory'],
        ['os-chart-qty-vs-discount'],
        ['os-grid-items'],
      ],
    },
    'os-page-3': {
      id: 'os-page-3',
      title: 'Fulfilment & Delivery',
      widgetRows: [
        ['os-text-fulfilment'],
        ['os-kpi-shipments', 'os-kpi-ontime', 'os-kpi-avg-transit'],
        ['os-chart-carrier-split', 'os-chart-ontime-by-carrier'],
        ['os-grid-shipments'],
      ],
    },
    'os-page-4': {
      id: 'os-page-4',
      title: 'Returns & Quality',
      widgetRows: [
        ['os-text-returns'],
        ['os-kpi-return-rate', 'os-kpi-returned-items', 'os-kpi-return-reasons'],
        ['os-chart-returns-by-category', 'os-chart-return-reasons'],
        ['os-grid-returns'],
      ],
    },
  },
  relationships: [
    {
      id: 'os-rel-orders-customers',
      sourceId: OS_ORDERS_SOURCE_ID,
      sourceField: 'customer_id',
      targetId: OS_CUSTOMERS_SOURCE_ID,
      targetField: 'customer_id',
      type: 'many-to-one',
    },
    {
      id: 'os-rel-orders-stores',
      sourceId: OS_ORDERS_SOURCE_ID,
      sourceField: 'store_id',
      targetId: OS_STORES_SOURCE_ID,
      targetField: 'store_id',
      type: 'many-to-one',
    },
    {
      id: 'os-rel-orderitems-orders',
      sourceId: OS_ORDER_ITEMS_SOURCE_ID,
      sourceField: 'order_id',
      targetId: OS_ORDERS_SOURCE_ID,
      targetField: 'order_id',
      type: 'many-to-one',
    },
    {
      id: 'os-rel-orderitems-products',
      sourceId: OS_ORDER_ITEMS_SOURCE_ID,
      sourceField: 'product_id',
      targetId: OS_PRODUCTS_SOURCE_ID,
      targetField: 'product_id',
      type: 'many-to-one',
    },
    {
      id: 'os-rel-shipments-orders',
      sourceId: OS_SHIPMENTS_SOURCE_ID,
      sourceField: 'order_id',
      targetId: OS_ORDERS_SOURCE_ID,
      targetField: 'order_id',
      type: 'many-to-one',
    },
  ],
  widgets: {
    'os-text-hero': {
      id: 'os-text-hero',
      kind: 'text',
      title: 'Office Supplies Dashboard',
      titleMode: 'manual' as const,
      sourceId: undefined,
      config: widgetConfig({ textTitleFontSize: 32, textTitleAlign: 'center' as const }),
    },
    'os-text-sales': {
      id: 'os-text-sales',
      kind: 'text',
      title: 'Sales & Margin Analysis',
      titleMode: 'manual' as const,
      sourceId: undefined,
      config: widgetConfig({ textTitleFontSize: 32, textTitleAlign: 'center' as const }),
    },
    'os-text-fulfilment': {
      id: 'os-text-fulfilment',
      kind: 'text',
      title: 'Fulfilment & Delivery',
      titleMode: 'manual' as const,
      sourceId: undefined,
      config: widgetConfig({ textTitleFontSize: 32, textTitleAlign: 'center' as const }),
    },
    'os-text-returns': {
      id: 'os-text-returns',
      kind: 'text',
      title: 'Returns & Quality',
      titleMode: 'manual' as const,
      sourceId: undefined,
      config: widgetConfig({ textTitleFontSize: 32, textTitleAlign: 'center' as const }),
    },
    'os-kpi-revenue': {
      id: 'os-kpi-revenue',
      kind: 'kpi',
      title: 'Total Revenue',
      titleMode: 'manual' as const,
      sourceId: OS_ORDER_ITEMS_SOURCE_ID,
      config: widgetConfig({
        kpiValueField: 'expr-os-line-net',
        kpiAggregation: 'sum',
        kpiCompact: true,
        kpiTrend: true,
        kpiSparkline: true,
        kpiSparklineField: 'order_datetime',
        kpiSparklineSourceId: OS_ORDERS_SOURCE_ID,
        kpiSparklineCumulative: true,
      }),
    },
    'os-kpi-orders': {
      id: 'os-kpi-orders',
      kind: 'kpi',
      title: 'Total Orders',
      titleMode: 'manual' as const,
      sourceId: OS_ORDER_ITEMS_SOURCE_ID,
      config: widgetConfig({
        kpiValueField: 'expr-os-order-count',
        kpiAggregation: 'sum',
        kpiCompact: true,
        kpiTrend: true,
        kpiSparkline: true,
        kpiSparklineField: 'order_datetime',
        kpiSparklineSourceId: OS_ORDERS_SOURCE_ID,
      }),
    },
    'os-kpi-customers': {
      id: 'os-kpi-customers',
      kind: 'kpi',
      title: 'Customers',
      titleMode: 'manual' as const,
      sourceId: OS_CUSTOMERS_SOURCE_ID,
      config: widgetConfig({
        kpiValueField: 'customer_id',
        kpiAggregation: 'count',
        kpiCompact: true,
      }),
    },
    'os-kpi-gm-pct': {
      id: 'os-kpi-gm-pct',
      kind: 'kpi',
      title: 'Gross Margin %',
      titleMode: 'manual' as const,
      sourceId: OS_ORDER_ITEMS_SOURCE_ID,
      config: widgetConfig({
        kpiValueField: 'expr-os-gm-pct',
        kpiAggregation: 'sum',
      }),
    },
    'os-kpi-shipments': {
      id: 'os-kpi-shipments',
      kind: 'kpi',
      title: 'Shipments',
      titleMode: 'manual' as const,
      sourceId: OS_SHIPMENTS_SOURCE_ID,
      config: widgetConfig({
        kpiValueField: 'shipment_id',
        kpiAggregation: 'count',
        kpiCompact: true,
      }),
    },
    'os-kpi-ontime': {
      id: 'os-kpi-ontime',
      kind: 'kpi',
      title: 'On-Time Rate',
      titleMode: 'manual' as const,
      sourceId: OS_SHIPMENTS_SOURCE_ID,
      config: widgetConfig({
        kpiValueField: 'expr-os-ontime-rate',
        kpiAggregation: 'sum',
      }),
    },
    'os-kpi-avg-transit': {
      id: 'os-kpi-avg-transit',
      kind: 'kpi',
      title: 'Avg Transit Days',
      titleMode: 'manual' as const,
      sourceId: OS_SHIPMENTS_SOURCE_ID,
      config: widgetConfig({
        kpiValueField: 'expr-os-transit-days',
        kpiAggregation: 'avg',
      }),
    },
    'os-kpi-return-rate': {
      id: 'os-kpi-return-rate',
      kind: 'kpi',
      title: 'Return Rate',
      titleMode: 'manual' as const,
      sourceId: OS_ORDER_ITEMS_SOURCE_ID,
      config: widgetConfig({
        kpiValueField: 'expr-os-return-rate',
        kpiAggregation: 'sum',
      }),
    },
    'os-kpi-returned-items': {
      id: 'os-kpi-returned-items',
      kind: 'kpi',
      title: 'Returned Items',
      titleMode: 'manual' as const,
      sourceId: OS_ORDER_ITEMS_SOURCE_ID,
      config: widgetConfig({
        kpiValueField: 'returned',
        kpiAggregation: 'count',
        kpiCompact: true,
      }),
    },
    'os-kpi-return-reasons': {
      id: 'os-kpi-return-reasons',
      kind: 'kpi',
      title: 'Return Reasons',
      titleMode: 'manual' as const,
      sourceId: OS_ORDER_ITEMS_SOURCE_ID,
      config: widgetConfig({
        kpiValueField: 'return_reason',
        kpiAggregation: 'count',
      }),
    },
    'os-filter-category': {
      id: 'os-filter-category',
      kind: 'filter',
      title: 'Category',
      titleMode: 'manual' as const,
      sourceId: OS_PRODUCTS_SOURCE_ID,
      config: widgetConfig({
        filterWidgetType: 'toggle',
        filterWidgetField: 'category',
      }),
    },
    'os-chart-revenue-trend': {
      id: 'os-chart-revenue-trend',
      kind: 'chart',
      title: 'Monthly Revenue',
      titleMode: 'manual' as const,
      sourceId: OS_ORDER_ITEMS_SOURCE_ID,
      config: widgetConfig({
        chartType: 'line',
        xField: 'order_datetime',
        xGroupBy: 'month',
        xFieldSourceId: OS_ORDERS_SOURCE_ID,
        yField: 'expr-os-line-net',
      }),
    },
    'os-chart-revenue-by-category': {
      id: 'os-chart-revenue-by-category',
      kind: 'chart',
      title: 'Revenue by Category',
      titleMode: 'manual' as const,
      sourceId: OS_ORDER_ITEMS_SOURCE_ID,
      config: widgetConfig({
        chartType: 'bar-stacked',
        xField: 'order_datetime',
        xGroupBy: 'quarter',
        xFieldSourceId: OS_ORDERS_SOURCE_ID,
        yField: 'expr-os-line-net',
        seriesField: 'category',
        seriesFieldSourceId: OS_PRODUCTS_SOURCE_ID,
      }),
    },
    'os-chart-revenue-by-region': {
      id: 'os-chart-revenue-by-region',
      kind: 'chart',
      title: 'Revenue by Region',
      titleMode: 'manual' as const,
      sourceId: OS_ORDER_ITEMS_SOURCE_ID,
      config: widgetConfig({
        chartType: 'pie',
        xField: 'region',
        xFieldSourceId: OS_CUSTOMERS_SOURCE_ID,
        yField: 'expr-os-line-net',
      }),
    },
    'os-chart-revenue-by-brand': {
      id: 'os-chart-revenue-by-brand',
      kind: 'chart',
      title: 'Top Brands by Revenue',
      titleMode: 'manual' as const,
      sourceId: OS_ORDER_ITEMS_SOURCE_ID,
      config: widgetConfig({
        chartType: 'bar',
        xField: 'brand',
        xFieldSourceId: OS_PRODUCTS_SOURCE_ID,
        yField: 'expr-os-line-net',
        barLayout: 'horizontal',
      }),
    },
    'os-chart-gm-by-subcategory': {
      id: 'os-chart-gm-by-subcategory',
      kind: 'chart',
      title: 'Margin % by Subcategory',
      titleMode: 'manual' as const,
      sourceId: OS_ORDER_ITEMS_SOURCE_ID,
      config: widgetConfig({
        chartType: 'bar',
        xField: 'subcategory',
        xFieldSourceId: OS_PRODUCTS_SOURCE_ID,
        yField: 'expr-os-gm-pct',
      }),
    },
    'os-chart-qty-vs-discount': {
      id: 'os-chart-qty-vs-discount',
      kind: 'chart',
      title: 'Qty vs Discount by Brand',
      titleMode: 'manual' as const,
      sourceId: OS_ORDER_ITEMS_SOURCE_ID,
      config: widgetConfig({
        chartType: 'scatter',
        xField: 'discount_pct',
        yField: 'quantity',
        seriesField: 'brand',
        seriesFieldSourceId: OS_PRODUCTS_SOURCE_ID,
        scatterSizeField: 'expr-os-line-net',
        scatterMinRadius: 4,
        scatterMaxRadius: 28,
      }),
    },
    'os-chart-carrier-split': {
      id: 'os-chart-carrier-split',
      kind: 'chart',
      title: 'Shipments by Carrier',
      titleMode: 'manual' as const,
      sourceId: OS_SHIPMENTS_SOURCE_ID,
      config: widgetConfig({
        chartType: 'pie',
        xField: 'carrier',
        yField: 'shipment_id',
        yAggregation: 'count',
      }),
    },
    'os-chart-ontime-by-carrier': {
      id: 'os-chart-ontime-by-carrier',
      kind: 'chart',
      title: 'On-Time Rate by Carrier',
      titleMode: 'manual' as const,
      sourceId: OS_SHIPMENTS_SOURCE_ID,
      config: widgetConfig({
        chartType: 'bar',
        xField: 'carrier',
        yField: 'expr-os-ontime-rate',
      }),
    },
    'os-chart-returns-by-category': {
      id: 'os-chart-returns-by-category',
      kind: 'chart',
      title: 'Return Rate by Category',
      titleMode: 'manual' as const,
      sourceId: OS_ORDER_ITEMS_SOURCE_ID,
      config: widgetConfig({
        chartType: 'bar',
        xField: 'category',
        xFieldSourceId: OS_PRODUCTS_SOURCE_ID,
        yField: 'expr-os-return-rate',
      }),
    },
    'os-chart-return-reasons': {
      id: 'os-chart-return-reasons',
      kind: 'chart',
      title: 'Return Reasons',
      titleMode: 'manual' as const,
      sourceId: OS_ORDER_ITEMS_SOURCE_ID,
      config: widgetConfig({
        chartType: 'donut',
        xField: 'return_reason',
        yField: 'order_item_id',
        yAggregation: 'count',
      }),
    },
    'os-grid-orders': {
      id: 'os-grid-orders',
      kind: 'grid',
      title: 'Orders',
      titleMode: 'manual' as const,
      sourceId: OS_ORDERS_SOURCE_ID,
      config: widgetConfig({
        columns: [
          { fieldId: 'order_id' },
          { fieldId: 'order_datetime' },
          { fieldId: 'customer_id' },
          { fieldId: 'status' },
          { fieldId: 'channel' },
        ],
        gridSortField: 'order_datetime',
        gridSortDirection: 'desc',
      }),
    },
    'os-grid-items': {
      id: 'os-grid-items',
      kind: 'grid',
      title: 'Order Items',
      titleMode: 'manual' as const,
      sourceId: OS_ORDER_ITEMS_SOURCE_ID,
      config: widgetConfig({
        columns: [
          { fieldId: 'order_item_id' },
          { fieldId: 'product_id' },
          { fieldId: 'quantity' },
          { fieldId: 'unit_price' },
          { fieldId: 'discount_pct' },
          { fieldId: 'expr-os-line-net' },
          { fieldId: 'expr-os-line-margin' },
        ],
        gridSortField: 'expr-os-line-net',
        gridSortDirection: 'desc',
        gridSummaryFields: {
          'expr-os-line-net': 'sum',
          'expr-os-line-margin': 'sum',
        },
      }),
    },
    'os-grid-shipments': {
      id: 'os-grid-shipments',
      kind: 'grid',
      title: 'Shipments',
      titleMode: 'manual' as const,
      sourceId: OS_SHIPMENTS_SOURCE_ID,
      config: widgetConfig({
        columns: [
          { fieldId: 'shipment_id' },
          { fieldId: 'order_id' },
          { fieldId: 'carrier' },
          { fieldId: 'ship_datetime' },
          { fieldId: 'delivery_datetime' },
          { fieldId: 'delayed' },
          { fieldId: 'expr-os-transit-days' },
        ],
        gridSortField: 'ship_datetime',
        gridSortDirection: 'desc',
      }),
    },
    'os-grid-returns': {
      id: 'os-grid-returns',
      kind: 'grid',
      title: 'Returned Items',
      titleMode: 'manual' as const,
      sourceId: OS_ORDER_ITEMS_SOURCE_ID,
      config: widgetConfig({
        columns: [
          { fieldId: 'order_item_id' },
          { fieldId: 'product_id' },
          { fieldId: 'return_reason' },
          { fieldId: 'unit_price' },
          { fieldId: 'discount_pct' },
        ],
        filters: [{ fieldId: 'returned', operator: 'equals', value: true }],
      }),
    },
  },
  expressionFields: [
    {
      id: 'expr-os-line-net',
      label: 'Net Revenue',
      sourceId: OS_ORDER_ITEMS_SOURCE_ID,
      isMeasure: false,
      type: 'number' as const,
      format: 'currency' as const,
      expression: {
        operator: 'multiply',
        inputs: [
          { id: 'unit_price' },
          { id: 'quantity' },
          {
            operator: 'subtract',
            inputs: [{ type: 'number', value: 1 }, { id: 'discount_pct' }],
          },
        ],
      },
    },
    {
      id: 'expr-os-line-cogs',
      label: 'COGS',
      sourceId: OS_ORDER_ITEMS_SOURCE_ID,
      isMeasure: false,
      type: 'number' as const,
      format: 'currency' as const,
      expression: {
        operator: 'multiply',
        inputs: [{ id: 'quantity' }, { id: 'unit_cost', joinSourceId: OS_PRODUCTS_SOURCE_ID }],
      },
    },
    {
      id: 'expr-os-line-margin',
      label: 'Gross Margin $',
      sourceId: OS_ORDER_ITEMS_SOURCE_ID,
      isMeasure: false,
      type: 'number' as const,
      format: 'currency' as const,
      expression: {
        operator: 'subtract',
        inputs: [{ id: 'expr-os-line-net' }, { id: 'expr-os-line-cogs' }],
      },
    },
    {
      id: 'expr-os-transit-days',
      label: 'Transit Days',
      sourceId: OS_SHIPMENTS_SOURCE_ID,
      isMeasure: false,
      type: 'number' as const,
      format: 'integer' as const,
      expression: {
        operator: 'datediff',
        inputs: [
          { type: 'string', value: 'day' },
          { id: 'ship_datetime' },
          { id: 'delivery_datetime' },
        ],
      },
    },
    {
      id: 'expr-os-gm-pct',
      label: 'Gross Margin %',
      sourceId: OS_ORDER_ITEMS_SOURCE_ID,
      isMeasure: true,
      type: 'number' as const,
      format: 'percent' as const,
      expression: {
        operator: 'divide',
        inputs: [
          { id: 'expr-os-line-margin', aggregation: 'sum' },
          { id: 'expr-os-line-net', aggregation: 'sum' },
        ],
      },
    },
    {
      id: 'expr-os-ontime-rate',
      label: 'On-Time Rate',
      sourceId: OS_SHIPMENTS_SOURCE_ID,
      isMeasure: true,
      type: 'number' as const,
      format: 'percent' as const,
      expression: {
        operator: 'divide',
        inputs: [
          {
            operator: 'if',
            inputs: [{ id: 'delayed' }, { type: 'number', value: 0 }, { type: 'number', value: 1 }],
          },
          { id: 'shipment_id', aggregation: 'count' },
        ],
      },
    },
    {
      id: 'expr-os-return-rate',
      label: 'Return Rate',
      sourceId: OS_ORDER_ITEMS_SOURCE_ID,
      isMeasure: true,
      type: 'number' as const,
      format: 'percent' as const,
      expression: {
        operator: 'divide',
        inputs: [
          {
            operator: 'if',
            inputs: [
              { id: 'returned' },
              { type: 'number', value: 1 },
              { type: 'number', value: 0 },
            ],
          },
          { id: 'order_item_id', aggregation: 'count' },
        ],
      },
    },
    {
      id: 'expr-os-order-count',
      label: 'Orders',
      sourceId: OS_ORDER_ITEMS_SOURCE_ID,
      isMeasure: true,
      type: 'number' as const,
      format: 'integer' as const,
      expression: { id: 'order_id', aggregation: 'count_distinct' },
    },
  ],
};
