import type { StudioState, RelativeDateValue } from '@mui/x-studio';
import {
  CUSTOMERS_SOURCE_ID,
  customersSource,
  ORDERS_SOURCE_ID,
  ordersSource,
  ORDER_ITEMS_SOURCE_ID,
  orderItemsSource,
  PRODUCTS_SOURCE_ID,
  productsSource,
  SHIPMENT_ITEMS_SOURCE_ID,
  shipmentItemsSource,
  SHIPMENTS_SOURCE_ID,
  shipmentsSource,
} from '../salesData';

export const INITIAL_STATE: Partial<StudioState> = {
  dashboard: {
    id: 'dashboard-sales',
    title: 'Sales Dashboard',
    activePageId: 'page-1',
  },
  pages: {
    'page-1': {
      id: 'page-1',
      title: 'Overview',
      widgetRows: [
        ['widget-text-hero'],
        ['widget-filter-country', 'widget-filter-date'],
        [
          'widget-kpi-orders',
          'widget-kpi-revenue',
          'widget-kpi-customers',
          'widget-kpi-avg-discount',
        ],
        ['widget-chart-revenue-by-category'],
        ['widget-chart-category', 'widget-chart-country'],
        ['widget-map-revenue-by-country'],
        ['widget-orders-grid'],
      ],
    },
    'page-2': {
      id: 'page-2',
      title: 'Products',
      widgetRows: [
        ['widget-text-products'],
        ['widget-filter2-category'],
        ['widget-kpi2-units-sold', 'widget-kpi2-margin', 'widget-kpi2-inventory-value'],
        ['widget-chart2-margin-by-category', 'widget-chart2-stock-by-category'],
        ['widget-chart2-price-vs-margin', 'widget-chart2-units-by-category'],
        ['widget-grid2-products'],
      ],
    },
    'page-3': {
      id: 'page-3',
      title: 'Logistics',
      widgetRows: [
        ['widget-text-logistics'],
        ['widget-kpi3-items-shipped', 'widget-kpi3-ontime'],
        ['widget-chart3-shipments-trend', 'widget-chart3-orders-by-country'],
        ['widget-chart3-shipments-by-status'],
        ['widget-grid3-shipments'],
      ],
    },
    'page-4': {
      id: 'page-4',
      title: 'Customers',
      widgetRows: [
        ['widget-text-customers'],
        ['widget-filter4-segment', 'widget-filter4-signup-date'],
        [
          'widget-kpi4-ltv',
          'widget-kpi4-customers',
          'widget-kpi4-avg-order',
          'widget-kpi4-enterprise',
        ],
        ['widget-chart4-acquisition', 'widget-chart4-revenue-by-segment'],
        ['widget-chart4-top-customers', 'widget-chart4-quarterly-segment'],
        ['widget-map4-uk-regions'],
        ['widget-grid4-top-customers'],
      ],
    },
    'page-5': {
      id: 'page-5',
      title: 'Analytics',
      widgetRows: [
        ['widget-text-analytics'],
        ['widget-pivot-revenue-by-segment'],
      ],
    },
  },
  dataSources: {
    [PRODUCTS_SOURCE_ID]: productsSource,
    [CUSTOMERS_SOURCE_ID]: customersSource,
    [ORDERS_SOURCE_ID]: ordersSource,
    [ORDER_ITEMS_SOURCE_ID]: orderItemsSource,
    [SHIPMENTS_SOURCE_ID]: shipmentsSource,
    [SHIPMENT_ITEMS_SOURCE_ID]: shipmentItemsSource,
  },
  relationships: [
    {
      id: 'rel-orders-customers',
      sourceId: ORDERS_SOURCE_ID,
      sourceField: 'customerId',
      targetId: CUSTOMERS_SOURCE_ID,
      targetField: 'id',
      type: 'many-to-one',
    },
    {
      id: 'rel-orderitems-orders',
      sourceId: ORDER_ITEMS_SOURCE_ID,
      sourceField: 'orderId',
      targetId: ORDERS_SOURCE_ID,
      targetField: 'id',
      type: 'many-to-one',
    },
    {
      id: 'rel-orderitems-products',
      sourceId: ORDER_ITEMS_SOURCE_ID,
      sourceField: 'productId',
      targetId: PRODUCTS_SOURCE_ID,
      targetField: 'id',
      type: 'many-to-one',
    },
    {
      id: 'rel-shipments-orders',
      sourceId: SHIPMENTS_SOURCE_ID,
      sourceField: 'orderId',
      targetId: ORDERS_SOURCE_ID,
      targetField: 'id',
      type: 'many-to-one',
    },
    {
      id: 'rel-shipmentitems-shipments',
      sourceId: SHIPMENT_ITEMS_SOURCE_ID,
      sourceField: 'shipmentId',
      targetId: SHIPMENTS_SOURCE_ID,
      targetField: 'id',
      type: 'many-to-one',
    },
    {
      id: 'rel-shipmentitems-orderitems',
      sourceId: SHIPMENT_ITEMS_SOURCE_ID,
      sourceField: 'orderItemId',
      targetId: ORDER_ITEMS_SOURCE_ID,
      targetField: 'id',
      type: 'many-to-one',
    },
  ],
  widgets: {
    // ── Page 1: Overview ────────────────────────────────────────────────────

    'widget-text-hero': {
      id: 'widget-text-hero',
      kind: 'text',
      title: 'Sales Performance Overview',
      titleMode: 'manual' as const,
      sourceId: undefined,
      config: {
        textTitleFontSize: 32,
        textTitleAlign: 'center' as const,
      },
    },

    'widget-text-products': {
      id: 'widget-text-products',
      kind: 'text',
      title: 'Product Portfolio',
      titleMode: 'manual' as const,
      sourceId: undefined,
      config: {
        textTitleFontSize: 32,
        textTitleAlign: 'center' as const,
      },
    },

    'widget-text-logistics': {
      id: 'widget-text-logistics',
      kind: 'text',
      title: 'Logistics Operations',
      titleMode: 'manual' as const,
      sourceId: undefined,
      config: {
        textTitleFontSize: 32,
        textTitleAlign: 'center' as const,
      },
    },

    'widget-text-customers': {
      id: 'widget-text-customers',
      kind: 'text',
      title: 'Customer Intelligence',
      titleMode: 'manual' as const,
      sourceId: undefined,
      config: {
        textTitleFontSize: 32,
        textTitleAlign: 'center' as const,
      },
    },

    'widget-filter-country': {
      id: 'widget-filter-country',
      kind: 'filter',
      title: 'Filter by Country',
      titleMode: 'manual',
      sourceId: ORDERS_SOURCE_ID,
      config: {
        filterWidgetType: 'toggle',
        filterWidgetField: 'expr-order-country',
      },
    },
    'widget-filter-date': {
      id: 'widget-filter-date',
      kind: 'filter',
      title: 'Order Date',
      titleMode: 'manual',
      sourceId: ORDERS_SOURCE_ID,
      config: {
        filterWidgetType: 'slider' as const,
        filterWidgetField: 'date',
      },
    },
    'widget-kpi-orders': {
      id: 'widget-kpi-orders',
      kind: 'kpi',
      title: 'Total Orders',
      sourceId: ORDERS_SOURCE_ID,
      config: {
        kpiValueField: 'status',
        kpiAggregation: 'count',
        kpiTrend: true,
        kpiSparkline: true,
        kpiSparklineField: 'date',
      },
    },
    'widget-kpi-revenue': {
      id: 'widget-kpi-revenue',
      kind: 'kpi',
      title: 'Total Revenue',
      sourceId: ORDER_ITEMS_SOURCE_ID,
      config: {
        kpiValueField: 'total',
        kpiAggregation: 'sum',
        kpiTrend: true,
        kpiSparkline: true,
        kpiSparklineField: 'date',
        kpiSparklineSourceId: ORDERS_SOURCE_ID,
        kpiSparklineCumulative: true,
      },
    },
    'widget-kpi-avg-discount': {
      id: 'widget-kpi-avg-discount',
      kind: 'kpi',
      title: 'Avg Discount',
      titleMode: 'manual',
      sourceId: ORDER_ITEMS_SOURCE_ID,
      config: {
        kpiValueField: 'discount',
        kpiAggregation: 'avg',
        kpiTrend: true,
        kpiTrendInvert: true,
        kpiSparkline: true,
        kpiSparklineField: 'date',
        kpiSparklineSourceId: ORDERS_SOURCE_ID,
        kpiSparklinePlotType: 'line',
        kpiSparklineGranularity: 'month',
      },
    },
    'widget-kpi-customers': {
      id: 'widget-kpi-customers',
      kind: 'kpi',
      title: 'Active Customers',
      sourceId: CUSTOMERS_SOURCE_ID,
      config: {
        kpiValueField: 'company',
        kpiAggregation: 'count',
        kpiTrend: true,
        kpiSparkline: true,
        kpiSparklineField: 'since',
        kpiSparklinePlotType: 'bar',
        kpiSparklineGranularity: 'month',
      },
    },
    'widget-chart-revenue-by-category': {
      id: 'widget-chart-revenue-by-category',
      kind: 'chart',
      title: 'Quarterly Revenue by Category',
      sourceId: ORDER_ITEMS_SOURCE_ID,
      config: {
        chartType: 'bar-stacked',
        xField: 'date',
        xGroupBy: 'quarter',
        yField: 'total',
        seriesField: 'category',
      },
    },
    'widget-chart-category': {
      id: 'widget-chart-category',
      kind: 'chart',
      title: 'Revenue by Category',
      sourceId: ORDER_ITEMS_SOURCE_ID,
      config: { chartType: 'donut', xField: 'category', yField: 'total' },
    },
    'widget-chart-country': {
      id: 'widget-chart-country',
      kind: 'chart',
      title: 'Revenue by Country',
      sourceId: ORDERS_SOURCE_ID,
      config: { chartType: 'pie', xField: 'expr-order-country', yField: 'total' },
    },
    'widget-orders-grid': {
      id: 'widget-orders-grid',
      kind: 'grid',
      title: 'Recent Orders',
      sourceId: ORDERS_SOURCE_ID,
      config: {
        columns: [
          { fieldId: 'id' },
          { fieldId: 'date' },
          { fieldId: 'customerId' },
          { fieldId: 'status' },
          { fieldId: 'total' },
        ],
        gridSortField: 'id',
        gridSortDirection: 'desc',
        gridSummaryFields: { id: 'count', total: 'sum' },
      },
    },

    // ── Page 2: Products ────────────────────────────────────────────────────

    'widget-kpi2-units-sold': {
      id: 'widget-kpi2-units-sold',
      kind: 'kpi',
      title: 'Units Sold',
      titleMode: 'manual',
      sourceId: ORDER_ITEMS_SOURCE_ID,
      config: {
        kpiValueField: 'quantity',
        kpiAggregation: 'sum',
        kpiCompact: true,
        kpiTrend: true,
        kpiSparkline: true,
        kpiSparklineField: 'date',
        kpiSparklineSourceId: ORDERS_SOURCE_ID,
        kpiSparklinePlotType: 'bar',
        kpiSparklineGranularity: 'month',
      },
    },
    'widget-kpi2-margin': {
      id: 'widget-kpi2-margin',
      kind: 'kpi',
      title: 'Avg Unit Margin',
      titleMode: 'manual',
      sourceId: PRODUCTS_SOURCE_ID,
      config: {
        kpiValueField: 'expr-product-margin',
        kpiAggregation: 'avg',
        kpiCompact: false,
        kpiTrend: true,
        kpiSparkline: true,
        kpiSparklineField: 'date',
        kpiSparklineSourceId: ORDERS_SOURCE_ID,
        kpiSparklinePlotType: 'line',
        kpiSparklineGranularity: 'quarter',
      },
    },
    'widget-kpi2-inventory-value': {
      id: 'widget-kpi2-inventory-value',
      kind: 'kpi',
      title: 'Total Inventory Value',
      titleMode: 'manual',
      sourceId: PRODUCTS_SOURCE_ID,
      config: {
        kpiValueField: 'expr-product-inventory-value',
        kpiAggregation: 'sum',
        kpiCompact: true,
      },
    },
    'widget-filter2-category': {
      id: 'widget-filter2-category',
      kind: 'filter',
      title: 'Category',
      titleMode: 'manual',
      sourceId: PRODUCTS_SOURCE_ID,
      config: {
        filterWidgetType: 'toggle' as const,
        filterWidgetField: 'category',
      },
    },
    'widget-chart2-margin-by-category': {
      id: 'widget-chart2-margin-by-category',
      kind: 'chart',
      title: 'Margin % by Category',
      titleMode: 'manual',
      sourceId: PRODUCTS_SOURCE_ID,
      config: {
        chartType: 'bar',
        xField: 'category',
        ySeries: [{ fieldId: 'expr-product-margin-pct' }],
        yField: 'expr-product-margin-pct',
      },
    },
    'widget-chart2-price-vs-margin': {
      id: 'widget-chart2-price-vs-margin',
      kind: 'chart',
      title: 'Price vs. Unit Margin',
      titleMode: 'manual',
      sourceId: PRODUCTS_SOURCE_ID,
      config: {
        chartType: 'scatter',
        xField: 'price',
        yField: 'expr-product-margin',
      },
    },
    'widget-chart2-stock-by-category': {
      id: 'widget-chart2-stock-by-category',
      kind: 'chart',
      title: 'Stock by Category',
      titleMode: 'manual',
      sourceId: PRODUCTS_SOURCE_ID,
      config: {
        chartType: 'bar',
        xField: 'product',
        yField: 'stock',
        barLayout: 'horizontal' as const,
      },
    },
    'widget-chart2-units-by-category': {
      id: 'widget-chart2-units-by-category',
      kind: 'chart',
      title: 'Units Sold by Category',
      titleMode: 'manual',
      sourceId: ORDER_ITEMS_SOURCE_ID,
      config: {
        chartType: 'bar',
        xField: 'category',
        yField: 'quantity',
      },
    },
    'widget-grid2-products': {
      id: 'widget-grid2-products',
      kind: 'grid',
      title: 'Product Catalogue',
      titleMode: 'manual',
      sourceId: PRODUCTS_SOURCE_ID,
      config: {
        columns: [
          { fieldId: 'product' },
          { fieldId: 'category' },
          { fieldId: 'price' },
          { fieldId: 'cost' },
          { fieldId: 'expr-product-margin' },
          { fieldId: 'expr-product-margin-pct' },
          { fieldId: 'stock' },
          { fieldId: 'reorderLevel' },
        ],
        crossFilterField: 'category',
        gridSummaryFields: { price: 'avg', cost: 'avg', stock: 'sum', reorderLevel: 'sum' },
      },
    },

    // ── Page 3: Logistics ────────────────────────────────────────────────────

    'widget-kpi3-items-shipped': {
      id: 'widget-kpi3-items-shipped',
      kind: 'kpi',
      title: 'Items Shipped',
      titleMode: 'manual',
      sourceId: SHIPMENTS_SOURCE_ID,
      config: {
        kpiValueField: 'itemCount',
        kpiAggregation: 'sum',
        kpiCompact: true,
        kpiTrend: true,
        kpiSparkline: true,
        kpiSparklineField: 'shipDate',
        kpiSparklinePlotType: 'bar',
        kpiSparklineGranularity: 'month',
      },
    },
    'widget-kpi3-ontime': {
      id: 'widget-kpi3-ontime',
      kind: 'kpi',
      title: 'On-Time Shipments',
      sourceId: SHIPMENTS_SOURCE_ID,
      config: {
        kpiValueField: 'onTime',
        kpiAggregation: 'avg',
        kpiTrend: true,
        kpiTrendInvert: true,
        kpiSparkline: true,
        kpiSparklineField: 'shipDate',
        kpiSparklinePlotType: 'line',
        kpiSparklineGranularity: 'month',
      },
    },
    'widget-chart3-shipments-trend': {
      id: 'widget-chart3-shipments-trend',
      kind: 'chart',
      title: 'Shipments by Carrier',
      titleMode: 'manual',
      sourceId: SHIPMENTS_SOURCE_ID,
      config: {
        chartType: 'bar-100',
        xField: 'shipDate',
        xGroupBy: 'month',
        yField: 'itemCount',
        seriesField: 'carrier',
      },
    },
    'widget-chart3-orders-by-country': {
      id: 'widget-chart3-orders-by-country',
      kind: 'chart',
      title: 'Revenue by Country Over Time',
      titleMode: 'manual',
      sourceId: ORDERS_SOURCE_ID,
      config: {
        chartType: 'area-stacked',
        xField: 'date',
        xGroupBy: 'quarter',
        yField: 'total',
        seriesField: 'expr-order-country',
      },
    },
    'widget-chart3-shipments-by-status': {
      id: 'widget-chart3-shipments-by-status',
      kind: 'chart',
      title: 'Shipments by Status',
      titleMode: 'manual',
      sourceId: SHIPMENTS_SOURCE_ID,
      config: {
        chartType: 'pie',
        xField: 'status',
        yField: 'itemCount',
      },
    },
    'widget-grid3-shipments': {
      id: 'widget-grid3-shipments',
      kind: 'grid',
      title: 'Shipment Log',
      titleMode: 'manual',
      sourceId: SHIPMENTS_SOURCE_ID,
      config: {
        columns: [
          { fieldId: 'id' },
          { fieldId: 'carrier' },
          { fieldId: 'shipDate' },
          { fieldId: 'estimatedDeliveryDate' },
          { fieldId: 'actualDeliveryDate' },
          { fieldId: 'status' },
          { fieldId: 'onTime' },
          { fieldId: 'itemCount' },
        ],
        gridSortField: 'shipDate',
        gridSortDirection: 'desc',
        gridSummaryFields: { id: 'count', itemCount: 'sum' },
        crossFilterField: 'carrier',
      },
    },

    // ── Page 4: Customers ────────────────────────────────────────────────────

    'widget-filter4-segment': {
      id: 'widget-filter4-segment',
      kind: 'filter',
      title: 'Filter by Segment',
      titleMode: 'manual',
      sourceId: CUSTOMERS_SOURCE_ID,
      config: {
        filterWidgetType: 'toggle',
        filterWidgetField: 'segment',
      },
    },
    'widget-filter4-signup-date': {
      id: 'widget-filter4-signup-date',
      kind: 'filter',
      title: 'Signup Date Range',
      titleMode: 'manual',
      sourceId: CUSTOMERS_SOURCE_ID,
      config: {
        filterWidgetType: 'date-range',
        filterWidgetField: 'since',
      },
    },

    'widget-kpi4-ltv': {
      id: 'widget-kpi4-ltv',
      kind: 'kpi',
      title: 'Lifetime Value',
      titleMode: 'manual',
      sourceId: ORDERS_SOURCE_ID,
      config: {
        kpiValueField: 'total',
        kpiAggregation: 'sum',
        kpiTrend: true,
        kpiSparkline: true,
        kpiSparklineField: 'date',
        kpiSparklinePlotType: 'line',
        kpiSparklineGranularity: 'quarter',
        kpiSparklineCumulative: true,
      },
    },
    'widget-kpi4-customers': {
      id: 'widget-kpi4-customers',
      kind: 'kpi',
      title: 'Customer Count',
      titleMode: 'manual',
      sourceId: CUSTOMERS_SOURCE_ID,
      config: {
        kpiValueField: 'company',
        kpiAggregation: 'count',
        kpiSparkline: true,
        kpiSparklineField: 'since',
        kpiSparklinePlotType: 'bar',
        kpiSparklineGranularity: 'year',
      },
    },
    'widget-kpi4-avg-order': {
      id: 'widget-kpi4-avg-order',
      kind: 'kpi',
      title: 'Avg Order Value',
      titleMode: 'manual',
      sourceId: ORDERS_SOURCE_ID,
      config: {
        kpiValueField: 'total',
        kpiAggregation: 'avg',
        kpiTrend: true,
        kpiSparkline: true,
        kpiSparklineField: 'date',
        kpiSparklinePlotType: 'line',
        kpiSparklineGranularity: 'quarter',
      },
    },
    'widget-kpi4-enterprise': {
      id: 'widget-kpi4-enterprise',
      kind: 'kpi',
      title: 'Enterprise Customers',
      titleMode: 'manual',
      sourceId: CUSTOMERS_SOURCE_ID,
      config: {
        kpiValueField: 'company',
        kpiAggregation: 'count',
        kpiSparkline: true,
        kpiSparklineField: 'since',
        kpiSparklinePlotType: 'bar',
        kpiSparklineGranularity: 'year',
      },
    },
    'widget-chart4-acquisition': {
      id: 'widget-chart4-acquisition',
      kind: 'chart',
      title: 'Customer Acquisition Over Time',
      titleMode: 'manual',
      sourceId: CUSTOMERS_SOURCE_ID,
      config: {
        chartType: 'bar',
        xField: 'since',
        xGroupBy: 'year',
        yField: 'company',
        yAggregation: 'count' as const,
      },
    },
    'widget-chart4-revenue-by-segment': {
      id: 'widget-chart4-revenue-by-segment',
      kind: 'chart',
      title: 'Revenue by Segment',
      titleMode: 'manual',
      sourceId: ORDERS_SOURCE_ID,
      config: {
        chartType: 'donut',
        xField: 'expr-order-segment',
        yField: 'total',
      },
    },
    'widget-chart4-top-customers': {
      id: 'widget-chart4-top-customers',
      kind: 'chart',
      title: 'Top Customers by Revenue',
      titleMode: 'manual',
      sourceId: ORDERS_SOURCE_ID,
      config: {
        chartType: 'bar',
        xField: 'expr-order-company',
        yField: 'total',
        barLayout: 'horizontal' as const,
      },
    },
    'widget-chart4-quarterly-segment': {
      id: 'widget-chart4-quarterly-segment',
      kind: 'chart',
      title: 'Quarterly Revenue by Segment',
      titleMode: 'manual',
      sourceId: ORDERS_SOURCE_ID,
      config: {
        chartType: 'area-stacked',
        xField: 'date',
        xGroupBy: 'quarter',
        yField: 'total',
        seriesField: 'expr-order-segment',
      },
    },
    'widget-grid4-top-customers': {
      id: 'widget-grid4-top-customers',
      kind: 'grid',
      title: 'Top Customers',
      titleMode: 'manual',
      sourceId: ORDERS_SOURCE_ID,
      config: {
        columns: [
          { fieldId: 'expr-order-company' },
          { fieldId: 'expr-order-segment' },
          { fieldId: 'expr-order-country' },
          { fieldId: 'id' },
          { fieldId: 'total' },
        ],
        gridGroupByField: 'expr-order-company',
        gridAggregations: { id: 'count', total: 'sum' },
        gridSortField: 'total',
        gridSortDirection: 'desc',
        gridSummaryFields: { total: 'sum' },
        crossFilterField: 'expr-order-company',
      },
    },

    // ── Custom geography example: England regions map ─────────────────────────
    // This widget uses the 'england-regions' geography registered via the
    // Studio `geographies` prop — demonstrating the developer API for
    // adding custom map types beyond the built-in world / usa / europe options.
    'widget-map4-uk-regions': {
      id: 'widget-map4-uk-regions',
      kind: 'map',
      title: 'UK Customers by Region',
      titleMode: 'manual',
      sourceId: CUSTOMERS_SOURCE_ID,
      config: {
        mapGeography: 'england-regions',
        mapCountryField: 'ukRegion',
        mapAggregation: 'count',
        mapColorScheme: 'blues',
        mapLegendPosition: 'bottom',
        mapLegendZeroMin: true,
        mapCrossFilterEmit: true,
      },
    },
    'widget-text-analytics': {
      id: 'widget-text-analytics',
      kind: 'text',
      title: 'Analytics',
      sourceId: undefined,
      config: { textContent: '## Analytics\nBreak down revenue by segment and order status.' },
    },
    'widget-map-revenue-by-country': {
      id: 'widget-map-revenue-by-country',
      kind: 'map',
      title: 'Revenue by Country',
      titleMode: 'manual',
      sourceId: ORDERS_SOURCE_ID,
      config: {
        mapCountryField: 'expr-order-country',
        mapValueField: 'total',
        mapAggregation: 'sum',
        mapGeography: 'world',
        mapColorScheme: 'blues',
        mapLegendZeroMin: true,
        mapCrossFilterEmit: true,
      },
    },
    'widget-pivot-revenue-by-segment': {
      id: 'widget-pivot-revenue-by-segment',
      kind: 'pivot',
      title: 'Revenue by Segment × Status',
      titleMode: 'manual',
      sourceId: ORDERS_SOURCE_ID,
      config: {
        pivotRowField: 'expr-order-segment',
        pivotColField: 'status',
        pivotValueField: 'total',
        pivotAggregation: 'sum',
        pivotShowTotals: true,
      },
    },
  },
  filters: [
    // Page 1 KPI date filters — "Last 12 months" window used for trend comparisons
    {
      id: 'filter-kpi-revenue-date',
      field: 'date',
      operator: 'greater_than_or_equal',
      value: {
        relative: true,
        amount: 12,
        unit: 'month',
        direction: 'past',
      } satisfies RelativeDateValue,
      scope: 'widget' as const,
      widgetId: 'widget-kpi-revenue',
      fieldType: 'date' as const,
      filterSourceId: ORDERS_SOURCE_ID,
    },
    {
      id: 'filter-kpi-orders-date',
      field: 'date',
      operator: 'greater_than_or_equal',
      value: {
        relative: true,
        amount: 12,
        unit: 'month',
        direction: 'past',
      } satisfies RelativeDateValue,
      scope: 'widget' as const,
      widgetId: 'widget-kpi-orders',
      fieldType: 'date' as const,
      filterSourceId: ORDERS_SOURCE_ID,
    },
    {
      id: 'filter-kpi-customers-date',
      field: 'date',
      operator: 'greater_than_or_equal',
      value: {
        relative: true,
        amount: 12,
        unit: 'month',
        direction: 'past',
      } satisfies RelativeDateValue,
      scope: 'widget' as const,
      widgetId: 'widget-kpi-customers',
      fieldType: 'date' as const,
      filterSourceId: ORDERS_SOURCE_ID,
    },
    {
      id: 'filter-kpi-avg-discount-date',
      field: 'date',
      operator: 'greater_than_or_equal',
      value: {
        relative: true,
        amount: 12,
        unit: 'month',
        direction: 'past',
      } satisfies RelativeDateValue,
      scope: 'widget' as const,
      widgetId: 'widget-kpi-avg-discount',
      fieldType: 'date' as const,
      filterSourceId: ORDERS_SOURCE_ID,
    },
    // Page 2 (Products) KPI date filters
    {
      id: 'filter-kpi2-margin-date',
      field: 'date',
      operator: 'greater_than_or_equal',
      value: {
        relative: true,
        amount: 12,
        unit: 'month',
        direction: 'past',
      } satisfies RelativeDateValue,
      scope: 'widget' as const,
      widgetId: 'widget-kpi2-margin',
      fieldType: 'date' as const,
      filterSourceId: ORDERS_SOURCE_ID,
    },
    {
      id: 'filter-kpi2-units-date',
      field: 'date',
      operator: 'greater_than_or_equal',
      value: {
        relative: true,
        amount: 12,
        unit: 'month',
        direction: 'past',
      } satisfies RelativeDateValue,
      scope: 'widget' as const,
      widgetId: 'widget-kpi2-units-sold',
      fieldType: 'date' as const,
      filterSourceId: ORDERS_SOURCE_ID,
    },
    {
      id: 'filter-stock-rank',
      field: 'product',
      filterMode: 'rank' as const,
      operator: 'equals',
      value: 10,
      rankDirection: 'bottom' as const,
      rankByField: 'stock',
      scope: 'widget' as const,
      widgetId: 'widget-chart2-stock-by-category',
      filterSourceId: PRODUCTS_SOURCE_ID,
    },
    // Page 3 (Logistics) KPI date filters
    {
      id: 'filter-kpi3-shipped-date',
      field: 'shipDate',
      operator: 'greater_than_or_equal',
      value: {
        relative: true,
        amount: 12,
        unit: 'month',
        direction: 'past',
      } satisfies RelativeDateValue,
      scope: 'widget' as const,
      widgetId: 'widget-kpi3-items-shipped',
      fieldType: 'date' as const,
      filterSourceId: SHIPMENTS_SOURCE_ID,
    },
    {
      id: 'filter-kpi3-ontime-date',
      field: 'shipDate',
      operator: 'greater_than_or_equal',
      value: {
        relative: true,
        amount: 12,
        unit: 'month',
        direction: 'past',
      } satisfies RelativeDateValue,
      scope: 'widget' as const,
      widgetId: 'widget-kpi3-ontime',
      fieldType: 'date' as const,
      filterSourceId: SHIPMENTS_SOURCE_ID,
    },
    {
      id: 'filter-country-rank',
      field: 'expr-order-country',
      filterMode: 'rank' as const,
      operator: 'equals',
      value: 5,
      rankDirection: 'top' as const,
      rankByField: 'total',
      scope: 'widget' as const,
      widgetId: 'widget-chart3-orders-by-country',
      filterSourceId: ORDERS_SOURCE_ID,
    },
    // Page 4 (Customers)
    {
      id: 'filter-kpi4-enterprise-segment',
      field: 'segment',
      operator: 'equals',
      value: 'Enterprise',
      scope: 'widget' as const,
      widgetId: 'widget-kpi4-enterprise',
      fieldType: 'string' as const,
      filterSourceId: CUSTOMERS_SOURCE_ID,
    },
    {
      id: 'filter-chart4-top-customers-rank',
      field: 'expr-order-company',
      filterMode: 'rank' as const,
      operator: 'equals',
      value: 12,
      rankDirection: 'top' as const,
      rankByField: 'total',
      scope: 'widget' as const,
      widgetId: 'widget-chart4-top-customers',
      filterSourceId: ORDERS_SOURCE_ID,
    },
    {
      id: 'filter-grid4-top-customers-rank',
      field: 'expr-order-company',
      filterMode: 'rank' as const,
      operator: 'equals',
      value: 20,
      rankDirection: 'top' as const,
      rankByField: 'total',
      scope: 'widget' as const,
      widgetId: 'widget-grid4-top-customers',
      filterSourceId: ORDERS_SOURCE_ID,
    },
  ],
  expressionFields: [
    {
      id: 'expr-order-country',
      label: 'Country',
      description: 'Country of the customer who placed the order',
      sourceId: ORDERS_SOURCE_ID,
      isMeasure: false,
      type: 'string',
      expression: {
        joinSourceId: CUSTOMERS_SOURCE_ID,
        fieldId: 'country',
      },
    },
    {
      id: 'expr-order-segment',
      label: 'Segment',
      description: 'Segment of the customer who placed the order',
      sourceId: ORDERS_SOURCE_ID,
      isMeasure: false,
      type: 'string',
      expression: {
        joinSourceId: CUSTOMERS_SOURCE_ID,
        fieldId: 'segment',
      },
    },
    {
      id: 'expr-order-company',
      label: 'Company',
      description: 'Company of the customer who placed the order',
      sourceId: ORDERS_SOURCE_ID,
      isMeasure: false,
      type: 'string',
      expression: {
        joinSourceId: CUSTOMERS_SOURCE_ID,
        fieldId: 'company',
      },
    },
    {
      id: 'expr-product-inventory-value',
      label: 'Inventory Value',
      description: 'Total stock value (stock × unit price)',
      sourceId: PRODUCTS_SOURCE_ID,
      isMeasure: false,
      type: 'number',
      format: 'currency',
      expression: {
        operator: 'multiply',
        inputs: [{ id: 'stock' }, { id: 'price' }],
      },
    },
    {
      id: 'expr-product-margin',
      label: 'Unit Margin',
      description: 'Selling price minus cost per unit',
      sourceId: PRODUCTS_SOURCE_ID,
      isMeasure: false,
      type: 'number',
      format: 'currency',
      expression: {
        operator: 'subtract',
        inputs: [{ id: 'price' }, { id: 'cost' }],
      },
    },
    {
      id: 'expr-product-margin-pct',
      label: 'Margin %',
      description: 'Gross margin as a percentage of selling price',
      sourceId: PRODUCTS_SOURCE_ID,
      isMeasure: false,
      type: 'number',
      format: 'percent',
      expression: {
        operator: 'divide',
        inputs: [
          {
            operator: 'subtract',
            inputs: [{ id: 'price' }, { id: 'cost' }],
          },
          { id: 'price' },
        ],
      },
    },
  ],
  shell: {
    // TODO: make these optional
    openDrawers: { data: false, compose: true, filters: true },
    selectedWidgetId: null,
    selectedFieldId: null,
    selectedSourceId: null,
  },
};
