import type { StudioState, RelativeDateValue } from '@mui/x-studio';
import {
  CUSTOMERS_SOURCE_ID,
  ORDERS_SOURCE_ID,
  ORDER_ITEMS_SOURCE_ID,
  PRODUCTS_SOURCE_ID,
  SHIPMENT_ITEMS_SOURCE_ID,
  SHIPMENTS_SOURCE_ID,
  generateSalesData,
} from '../salesData';
import {
  CRM_CONTACTS_SOURCE_ID,
  CRM_DEALS_SOURCE_ID,
  CRM_ACTIVITIES_SOURCE_ID,
  CRM_DEAL_TRANSITIONS_SOURCE_ID,
  generateCrmData,
} from '../crmData';

const {
  customersSource,
  productsSource,
  ordersSource,
  orderItemsSource,
  shipmentsSource,
  shipmentItemsSource,
} = generateSalesData({ seed: 42, orderCount: 1000 });

const { contactsSource, dealsSource, activitiesSource, dealTransitionsSource } = generateCrmData({
  seed: 42,
  orderCount: 1000,
});

export const INITIAL_STATE: Partial<StudioState> = {
  dashboard: {
    id: 'dashboard-sales',
    title: 'Sales Dashboard',
    activePageId: 'page-1',
  },
  pages: {
    'page-1': {
      id: 'page-1',
      title: 'Sales Overview',
      widgetRows: [
        ['widget-text-hero'],
        ['widget-alert-banner'],
        ['widget-filter-country', 'widget-filter-date'],
        [
          'widget-kpi-orders',
          'widget-kpi-revenue',
          'widget-kpi-customers',
          'widget-kpi-avg-discount',
        ],
        ['widget-chart-revenue-by-category'],
        ['widget-chart-category', 'widget-chart-country'],
        ['widget-map-revenue-by-country'],
        ['widget-orders-grid'],
      ],
    },
    'page-2': {
      id: 'page-2',
      title: 'Sales Products',
      widgetRows: [
        ['widget-text-products'],
        ['widget-filter2-category'],
        ['widget-kpi2-units-sold', 'widget-kpi2-margin', 'widget-kpi2-inventory-value'],
        ['widget-chart2-margin-by-category', 'widget-chart2-stock-by-category'],
        ['widget-chart2-price-vs-margin', 'widget-chart2-units-by-category'],
        ['widget-chart2-discount-heatmap'],
        ['widget-grid2-products'],
      ],
    },
    'page-3': {
      id: 'page-3',
      title: 'Sales Logistics',
      widgetRows: [
        ['widget-text-logistics'],
        ['widget-kpi3-items-shipped', 'widget-kpi3-ontime'],
        ['widget-chart3-shipments-trend', 'widget-chart3-orders-by-country'],
        ['widget-chart3-shipments-by-status'],
        ['widget-chart3-delivery-heatmap'],
        ['widget-grid3-shipments'],
      ],
    },
    'page-4': {
      id: 'page-4',
      title: 'Sales Customers',
      widgetRows: [
        ['widget-text-customers'],
        ['widget-filter4-segment', 'widget-filter4-signup-date'],
        [
          'widget-kpi4-ltv',
          'widget-kpi4-customers',
          'widget-kpi4-avg-order',
          'widget-kpi4-enterprise',
        ],
        ['widget-chart4-acquisition', 'widget-chart4-revenue-by-segment'],
        ['widget-chart4-top-customers', 'widget-chart4-quarterly-segment'],
        ['widget-grid4-top-customers'],
      ],
    },
    'page-5': {
      id: 'page-5',
      title: 'Sales Analytics',
      widgetRows: [
        ['widget-text-analytics'],
        ['widget-pivot-revenue-by-segment'],
        ['widget-chart5-order-funnel', 'widget-chart5-revenue-mixed'],
        ['widget-chart5-revenue-vs-stock-blend'],
      ],
    },
    'page-6': {
      id: 'page-6',
      title: 'CRM Pipeline',
      widgetRows: [
        ['widget-text-crm-pipeline'],
        ['widget-kpi6-open-deals', 'widget-kpi6-pipeline-value', 'widget-kpi6-win-rate'],
        ['widget-chart6-deals-by-stage', 'widget-chart6-value-by-stage'],
        ['widget-chart6-stage-conversion', 'widget-chart6-time-in-stage'],
        ['widget-chart6-stage-flow'],
        ['widget-grid6-deals'],
      ],
    },
    'page-7': {
      id: 'page-7',
      title: 'CRM Contacts',
      widgetRows: [
        ['widget-text-crm-contacts'],
        ['widget-kpi7-total-contacts', 'widget-kpi7-open-activities'],
        ['widget-chart7-contacts-by-dept', 'widget-chart7-contacts-by-role'],
        ['widget-grid7-contacts'],
      ],
    },
    'page-8': {
      id: 'page-8',
      title: 'Customer 360',
      widgetRows: [
        ['widget-text-customer360'],
        ['widget-kpi8-pipeline-value', 'widget-kpi8-avg-duration'],
        ['widget-chart8-pipeline-by-segment', 'widget-chart8-deals-by-country'],
        ['widget-chart8-revenue-by-segment', 'widget-chart8-pipeline-by-contact-role'],
        ['widget-chart8-activities-by-type', 'widget-chart8-activities-by-outcome'],
        ['widget-chart8-activity-by-department'],
        ['widget-grid8-cross-db-deals'],
      ],
    },
  },
  dataSources: {
    [PRODUCTS_SOURCE_ID]: productsSource,
    [CUSTOMERS_SOURCE_ID]: customersSource,
    [ORDERS_SOURCE_ID]: ordersSource,
    [ORDER_ITEMS_SOURCE_ID]: orderItemsSource,
    [SHIPMENTS_SOURCE_ID]: shipmentsSource,
    [SHIPMENT_ITEMS_SOURCE_ID]: shipmentItemsSource,
    [CRM_CONTACTS_SOURCE_ID]: contactsSource,
    [CRM_DEALS_SOURCE_ID]: dealsSource,
    [CRM_ACTIVITIES_SOURCE_ID]: activitiesSource,
    [CRM_DEAL_TRANSITIONS_SOURCE_ID]: dealTransitionsSource,
  },
  relationships: [
    {
      id: 'rel-orders-customers',
      sourceId: ORDERS_SOURCE_ID,
      sourceField: 'customerId',
      targetId: CUSTOMERS_SOURCE_ID,
      targetField: 'id',
      type: 'many-to-one',
    },
    {
      id: 'rel-orderitems-orders',
      sourceId: ORDER_ITEMS_SOURCE_ID,
      sourceField: 'orderId',
      targetId: ORDERS_SOURCE_ID,
      targetField: 'id',
      type: 'many-to-one',
    },
    {
      id: 'rel-orderitems-products',
      sourceId: ORDER_ITEMS_SOURCE_ID,
      sourceField: 'productId',
      targetId: PRODUCTS_SOURCE_ID,
      targetField: 'id',
      type: 'many-to-one',
    },
    {
      id: 'rel-shipments-orders',
      sourceId: SHIPMENTS_SOURCE_ID,
      sourceField: 'orderId',
      targetId: ORDERS_SOURCE_ID,
      targetField: 'id',
      type: 'many-to-one',
    },
    {
      id: 'rel-shipmentitems-shipments',
      sourceId: SHIPMENT_ITEMS_SOURCE_ID,
      sourceField: 'shipmentId',
      targetId: SHIPMENTS_SOURCE_ID,
      targetField: 'id',
      type: 'many-to-one',
    },
    {
      id: 'rel-shipmentitems-orderitems',
      sourceId: SHIPMENT_ITEMS_SOURCE_ID,
      sourceField: 'orderItemId',
      targetId: ORDER_ITEMS_SOURCE_ID,
      targetField: 'id',
      type: 'many-to-one',
    },
    // M:N relationship so "ship date" cross-filters can apply to order-items widgets.
    // ORDER_ITEMS ↔ SHIPMENTS via SHIPMENT_ITEMS junction
    {
      id: 'rel-orderitems-shipments-mn',
      sourceId: ORDER_ITEMS_SOURCE_ID,
      sourceField: 'id',
      targetId: SHIPMENTS_SOURCE_ID,
      targetField: 'id',
      type: 'many-to-many',
      junctionSourceId: SHIPMENT_ITEMS_SOURCE_ID,
      junctionSourceField: 'orderItemId',
      junctionTargetField: 'shipmentId',
    },
    // CRM-internal relationships (all within the CRM database — SQL JOINs work server-side)
    {
      id: 'rel-crm-activities-contacts',
      sourceId: CRM_ACTIVITIES_SOURCE_ID,
      sourceField: 'contactId',
      targetId: CRM_CONTACTS_SOURCE_ID,
      targetField: 'id',
      type: 'many-to-one',
    },
    {
      id: 'rel-crm-activities-deals',
      sourceId: CRM_ACTIVITIES_SOURCE_ID,
      sourceField: 'dealId',
      targetId: CRM_DEALS_SOURCE_ID,
      targetField: 'id',
      type: 'many-to-one',
    },
    {
      id: 'rel-crm-deals-contacts',
      sourceId: CRM_DEALS_SOURCE_ID,
      sourceField: 'primaryContactId',
      targetId: CRM_CONTACTS_SOURCE_ID,
      targetField: 'id',
      type: 'many-to-one',
    },
    // Cross-database joins: CRM (deals/contacts) → Sales (customers)
    // Both CRM sources share a `customerId` FK that maps to `customers.id`
    {
      id: 'rel-crm-deals-customers',
      sourceId: CRM_DEALS_SOURCE_ID,
      sourceField: 'customerId',
      targetId: CUSTOMERS_SOURCE_ID,
      targetField: 'id',
      type: 'many-to-one',
    },
    {
      id: 'rel-crm-contacts-customers',
      sourceId: CRM_CONTACTS_SOURCE_ID,
      sourceField: 'customerId',
      targetId: CUSTOMERS_SOURCE_ID,
      targetField: 'id',
      type: 'many-to-one',
    },
  ],
  widgets: {
    // ── Page 1: Overview ────────────────────────────────────────────────────

    'widget-text-hero': {
      id: 'widget-text-hero',
      kind: 'text',
      title: 'Sales Performance Overview',
      titleMode: 'manual' as const,
      sourceId: undefined,
      config: {
        textTitleFontSize: 32,
        textTitleAlign: 'center' as const,
      },
    },

    'widget-text-products': {
      id: 'widget-text-products',
      kind: 'text',
      title: 'Product Portfolio',
      titleMode: 'manual' as const,
      sourceId: undefined,
      config: {
        textTitleFontSize: 32,
        textTitleAlign: 'center' as const,
      },
    },

    'widget-text-logistics': {
      id: 'widget-text-logistics',
      kind: 'text',
      title: 'Logistics Operations',
      titleMode: 'manual' as const,
      sourceId: undefined,
      config: {
        textTitleFontSize: 32,
        textTitleAlign: 'center' as const,
      },
    },

    'widget-text-customers': {
      id: 'widget-text-customers',
      kind: 'text',
      title: 'Customer Intelligence',
      titleMode: 'manual' as const,
      sourceId: undefined,
      config: {
        textTitleFontSize: 32,
        textTitleAlign: 'center' as const,
      },
    },

    'widget-filter-country': {
      id: 'widget-filter-country',
      kind: 'filter',
      title: 'Filter by Country',
      titleMode: 'manual',
      sourceId: ORDERS_SOURCE_ID,
      config: {
        filterWidgetType: 'toggle',
        filterWidgetField: 'expr-order-country',
      },
    },
    'widget-filter-date': {
      id: 'widget-filter-date',
      kind: 'filter',
      title: 'Order Date',
      titleMode: 'manual',
      sourceId: ORDERS_SOURCE_ID,
      config: {
        filterWidgetType: 'slider' as const,
        filterWidgetField: 'date',
      },
    },
    'widget-kpi-orders': {
      id: 'widget-kpi-orders',
      kind: 'kpi',
      title: 'Total Orders',
      sourceId: ORDERS_SOURCE_ID,
      config: {
        kpiValueField: 'status',
        kpiAggregation: 'count',
        kpiTrend: true,
        kpiSparkline: true,
        kpiSparklinePlotType: 'gauge',
        kpiTargetValue: 500,
      },
    },
    'widget-kpi-revenue': {
      id: 'widget-kpi-revenue',
      kind: 'kpi',
      title: 'Total Revenue',
      sourceId: ORDER_ITEMS_SOURCE_ID,
      config: {
        kpiValueField: 'total',
        kpiAggregation: 'sum',
        kpiTrend: true,
        kpiSparkline: true,
        kpiSparklineField: 'date',
        kpiSparklineSourceId: ORDERS_SOURCE_ID,
        kpiSparklineCumulative: true,
      },
    },
    'widget-kpi-avg-discount': {
      id: 'widget-kpi-avg-discount',
      kind: 'kpi',
      title: 'Avg Discount',
      titleMode: 'manual',
      sourceId: ORDER_ITEMS_SOURCE_ID,
      config: {
        kpiValueField: 'discount',
        kpiAggregation: 'avg',
        kpiTrend: true,
        kpiTrendInvert: true,
        kpiSparkline: true,
        kpiSparklineField: 'date',
        kpiSparklineSourceId: ORDERS_SOURCE_ID,
        kpiSparklinePlotType: 'line',
        kpiSparklineGranularity: 'month',
      },
    },
    'widget-kpi-customers': {
      id: 'widget-kpi-customers',
      kind: 'kpi',
      title: 'Active Customers',
      sourceId: CUSTOMERS_SOURCE_ID,
      config: {
        kpiValueField: 'company',
        kpiAggregation: 'count',
        kpiTrend: true,
        kpiSparkline: true,
        kpiSparklineField: 'since',
        kpiSparklinePlotType: 'bar',
        kpiSparklineGranularity: 'month',
      },
    },
    // Example custom widget (registered via `<Studio customWidgets={[...]} />`).
    // Renders as a full-bleed banner whose severity is driven by the summed order
    // total over the most recent 7 days of data. Higher values are better:
    // ≥100k = success, ≥50k = warning (demo data ~65k lands here), ≥25k = error.
    // hideBelow:'warning' collapses the row in view mode when everything is fine.
    'widget-alert-banner': {
      id: 'widget-alert-banner',
      kind: 'alert-banner',
      title: 'Sales Alert',
      titleMode: 'manual' as const,
      sourceId: ORDERS_SOURCE_ID,
      config: {
        customConfig: {
          message: 'Recent order volume was {value} over the last week.',
          valueField: 'total',
          aggregation: 'sum',
          dateField: 'date',
          lookbackDays: 7,
          thresholdSuccess: 100000,
          thresholdWarning: 50000,
          thresholdError: 25000,
          hideBelow: 'warning',
        },
      },
    },
    'widget-chart-revenue-by-category': {
      id: 'widget-chart-revenue-by-category',
      kind: 'chart',
      title: 'Quarterly Revenue by Category',
      sourceId: ORDER_ITEMS_SOURCE_ID,
      config: {
        chartType: 'bar-stacked',
        xField: 'date',
        xGroupBy: 'quarter',
        yField: 'total',
        seriesField: 'category',
      },
    },
    'widget-chart-category': {
      id: 'widget-chart-category',
      kind: 'chart',
      title: 'Revenue by Category',
      sourceId: ORDER_ITEMS_SOURCE_ID,
      config: { chartType: 'donut', xField: 'category', yField: 'total' },
    },
    'widget-chart-country': {
      id: 'widget-chart-country',
      kind: 'chart',
      title: 'Revenue by Status',
      sourceId: ORDERS_SOURCE_ID,
      config: { chartType: 'donut', xField: 'status', yField: 'total' },
    },
    'widget-orders-grid': {
      id: 'widget-orders-grid',
      kind: 'grid',
      title: 'Recent Orders',
      sourceId: ORDERS_SOURCE_ID,
      config: {
        columns: [
          { fieldId: 'id' },
          { fieldId: 'date' },
          { fieldId: 'customerId' },
          { fieldId: 'status' },
          { fieldId: 'total' },
        ],
        gridSortField: 'id',
        gridSortDirection: 'desc',
        gridSummaryFields: { id: 'count', total: 'sum' },
      },
    },

    // ── Page 2: Products ────────────────────────────────────────────────────

    'widget-kpi2-units-sold': {
      id: 'widget-kpi2-units-sold',
      kind: 'kpi',
      title: 'Units Sold',
      titleMode: 'manual',
      sourceId: ORDER_ITEMS_SOURCE_ID,
      config: {
        kpiValueField: 'quantity',
        kpiAggregation: 'sum',
        kpiCompact: true,
        kpiTrend: true,
        kpiSparkline: true,
        kpiSparklineField: 'date',
        kpiSparklineSourceId: ORDERS_SOURCE_ID,
        kpiSparklinePlotType: 'bar',
        kpiSparklineGranularity: 'month',
      },
    },
    'widget-kpi2-margin': {
      id: 'widget-kpi2-margin',
      kind: 'kpi',
      title: 'Avg Unit Margin',
      titleMode: 'manual',
      sourceId: PRODUCTS_SOURCE_ID,
      config: {
        kpiValueField: 'expr-product-margin',
        kpiAggregation: 'avg',
        kpiCompact: false,
        kpiTrend: true,
      },
    },
    'widget-kpi2-inventory-value': {
      id: 'widget-kpi2-inventory-value',
      kind: 'kpi',
      title: 'Total Inventory Value',
      titleMode: 'manual',
      sourceId: PRODUCTS_SOURCE_ID,
      config: {
        kpiValueField: 'expr-product-inventory-value',
        kpiAggregation: 'sum',
        kpiCompact: true,
      },
    },
    'widget-filter2-category': {
      id: 'widget-filter2-category',
      kind: 'filter',
      title: 'Category',
      titleMode: 'manual',
      sourceId: PRODUCTS_SOURCE_ID,
      config: {
        filterWidgetType: 'toggle' as const,
        filterWidgetField: 'category',
      },
    },
    'widget-chart2-margin-by-category': {
      id: 'widget-chart2-margin-by-category',
      kind: 'chart',
      title: 'Margin % by Category',
      titleMode: 'manual',
      sourceId: PRODUCTS_SOURCE_ID,
      config: {
        chartType: 'bar',
        xField: 'category',
        ySeries: [{ fieldId: 'expr-product-margin-pct' }],
        yField: 'expr-product-margin-pct',
        yAggregation: 'avg',
      },
    },
    'widget-chart2-price-vs-margin': {
      id: 'widget-chart2-price-vs-margin',
      kind: 'chart',
      title: 'Price vs. Unit Margin',
      titleMode: 'manual',
      sourceId: PRODUCTS_SOURCE_ID,
      config: {
        chartType: 'scatter',
        xField: 'price',
        yField: 'expr-product-margin',
      },
    },
    'widget-chart2-stock-by-category': {
      id: 'widget-chart2-stock-by-category',
      kind: 'chart',
      title: 'Stock by Category',
      titleMode: 'manual',
      sourceId: PRODUCTS_SOURCE_ID,
      config: {
        chartType: 'bar',
        xField: 'product',
        yField: 'stock',
        barLayout: 'horizontal' as const,
      },
    },
    'widget-chart2-units-by-category': {
      id: 'widget-chart2-units-by-category',
      kind: 'chart',
      title: 'Units Sold by Category',
      titleMode: 'manual',
      sourceId: ORDER_ITEMS_SOURCE_ID,
      config: {
        chartType: 'bar',
        xField: 'category',
        yField: 'quantity',
      },
    },
    'widget-grid2-products': {
      id: 'widget-grid2-products',
      kind: 'grid',
      title: 'Product Catalogue',
      titleMode: 'manual',
      sourceId: PRODUCTS_SOURCE_ID,
      config: {
        columns: [
          { fieldId: 'product' },
          { fieldId: 'category' },
          { fieldId: 'price' },
          { fieldId: 'cost' },
          { fieldId: 'expr-product-margin' },
          { fieldId: 'expr-product-margin-pct' },
          { fieldId: 'stock' },
          { fieldId: 'reorderLevel' },
        ],
        crossFilterField: 'category',
        gridSummaryFields: { price: 'avg', cost: 'avg', stock: 'sum', reorderLevel: 'sum' },
      },
    },

    // ── Page 3: Logistics ────────────────────────────────────────────────────

    'widget-kpi3-items-shipped': {
      id: 'widget-kpi3-items-shipped',
      kind: 'kpi',
      title: 'Items Shipped',
      titleMode: 'manual',
      sourceId: SHIPMENTS_SOURCE_ID,
      config: {
        kpiValueField: 'itemCount',
        kpiAggregation: 'sum',
        kpiCompact: true,
        kpiTrend: true,
        kpiSparkline: true,
        kpiSparklineField: 'shipDate',
        kpiSparklinePlotType: 'bar',
        kpiSparklineGranularity: 'month',
      },
    },
    'widget-kpi3-ontime': {
      id: 'widget-kpi3-ontime',
      kind: 'kpi',
      title: 'On-Time Shipments',
      sourceId: SHIPMENTS_SOURCE_ID,
      config: {
        kpiValueField: 'onTime',
        kpiAggregation: 'avg',
        kpiTrend: true,
        kpiTrendInvert: true,
        kpiSparkline: true,
        kpiSparklineField: 'shipDate',
        kpiSparklinePlotType: 'line',
        kpiSparklineGranularity: 'month',
      },
    },
    'widget-chart3-shipments-trend': {
      id: 'widget-chart3-shipments-trend',
      kind: 'chart',
      title: 'Shipments by Carrier',
      titleMode: 'manual',
      sourceId: SHIPMENTS_SOURCE_ID,
      config: {
        chartType: 'bar-100',
        xField: 'shipDate',
        xGroupBy: 'month',
        yField: 'itemCount',
        seriesField: 'carrier',
      },
    },
    'widget-chart3-orders-by-country': {
      id: 'widget-chart3-orders-by-country',
      kind: 'chart',
      title: 'Revenue by Country Over Time',
      titleMode: 'manual',
      sourceId: ORDERS_SOURCE_ID,
      config: {
        chartType: 'area-stacked',
        xField: 'date',
        xGroupBy: 'quarter',
        yField: 'total',
        seriesField: 'expr-order-country',
      },
    },
    'widget-chart3-shipments-by-status': {
      id: 'widget-chart3-shipments-by-status',
      kind: 'chart',
      title: 'Shipments by Status',
      titleMode: 'manual',
      sourceId: SHIPMENTS_SOURCE_ID,
      config: {
        chartType: 'pie',
        xField: 'status',
        yField: 'itemCount',
      },
    },
    'widget-grid3-shipments': {
      id: 'widget-grid3-shipments',
      kind: 'grid',
      title: 'Shipment Log',
      titleMode: 'manual',
      sourceId: SHIPMENTS_SOURCE_ID,
      config: {
        columns: [
          { fieldId: 'id' },
          { fieldId: 'carrier' },
          { fieldId: 'shipDate' },
          { fieldId: 'estimatedDeliveryDate' },
          { fieldId: 'actualDeliveryDate' },
          { fieldId: 'status' },
          { fieldId: 'onTime' },
          { fieldId: 'itemCount' },
        ],
        gridSortField: 'shipDate',
        gridSortDirection: 'desc',
        gridSummaryFields: { id: 'count', itemCount: 'sum' },
        crossFilterField: 'carrier',
      },
    },

    // ── Page 4: Customers ────────────────────────────────────────────────────

    'widget-filter4-segment': {
      id: 'widget-filter4-segment',
      kind: 'filter',
      title: 'Filter by Segment',
      titleMode: 'manual',
      sourceId: CUSTOMERS_SOURCE_ID,
      config: {
        filterWidgetType: 'toggle',
        filterWidgetField: 'segment',
      },
    },
    'widget-filter4-signup-date': {
      id: 'widget-filter4-signup-date',
      kind: 'filter',
      title: 'Signup Date Range',
      titleMode: 'manual',
      sourceId: CUSTOMERS_SOURCE_ID,
      config: {
        filterWidgetType: 'date-range',
        filterWidgetField: 'since',
      },
    },

    'widget-kpi4-ltv': {
      id: 'widget-kpi4-ltv',
      kind: 'kpi',
      title: 'Lifetime Value',
      titleMode: 'manual',
      sourceId: ORDERS_SOURCE_ID,
      config: {
        kpiValueField: 'total',
        kpiAggregation: 'sum',
        kpiTrend: true,
        kpiSparkline: true,
        kpiSparklineField: 'date',
        kpiSparklinePlotType: 'line',
        kpiSparklineGranularity: 'quarter',
        kpiSparklineCumulative: true,
      },
    },
    'widget-kpi4-customers': {
      id: 'widget-kpi4-customers',
      kind: 'kpi',
      title: 'Customer Count',
      titleMode: 'manual',
      sourceId: CUSTOMERS_SOURCE_ID,
      config: {
        kpiValueField: 'company',
        kpiAggregation: 'count',
        kpiSparkline: true,
        kpiSparklineField: 'since',
        kpiSparklinePlotType: 'bar',
        kpiSparklineGranularity: 'year',
      },
    },
    'widget-kpi4-avg-order': {
      id: 'widget-kpi4-avg-order',
      kind: 'kpi',
      title: 'Avg Order Value',
      titleMode: 'manual',
      sourceId: ORDERS_SOURCE_ID,
      config: {
        kpiValueField: 'total',
        kpiAggregation: 'avg',
        kpiTrend: true,
        kpiSparkline: true,
        kpiSparklineField: 'date',
        kpiSparklinePlotType: 'line',
        kpiSparklineGranularity: 'quarter',
      },
    },
    'widget-kpi4-enterprise': {
      id: 'widget-kpi4-enterprise',
      kind: 'kpi',
      title: 'Enterprise Customers',
      titleMode: 'manual',
      sourceId: CUSTOMERS_SOURCE_ID,
      config: {
        kpiValueField: 'company',
        kpiAggregation: 'count',
        kpiSparkline: true,
        kpiSparklineField: 'since',
        kpiSparklinePlotType: 'bar',
        kpiSparklineGranularity: 'year',
      },
    },
    'widget-chart4-acquisition': {
      id: 'widget-chart4-acquisition',
      kind: 'chart',
      title: 'Customer Acquisition Over Time',
      titleMode: 'manual',
      sourceId: CUSTOMERS_SOURCE_ID,
      config: {
        chartType: 'bar',
        xField: 'since',
        xGroupBy: 'year',
        yField: 'company',
        yAggregation: 'count' as const,
      },
    },
    'widget-chart4-revenue-by-segment': {
      id: 'widget-chart4-revenue-by-segment',
      kind: 'chart',
      title: 'Revenue by Segment',
      titleMode: 'manual',
      sourceId: ORDERS_SOURCE_ID,
      config: {
        chartType: 'donut',
        xField: 'expr-order-segment',
        yField: 'total',
      },
    },
    'widget-chart4-top-customers': {
      id: 'widget-chart4-top-customers',
      kind: 'chart',
      title: 'Top Customers by Revenue',
      titleMode: 'manual',
      sourceId: ORDERS_SOURCE_ID,
      config: {
        chartType: 'bar',
        xField: 'expr-order-company',
        yField: 'total',
        barLayout: 'horizontal' as const,
      },
    },
    'widget-chart4-quarterly-segment': {
      id: 'widget-chart4-quarterly-segment',
      kind: 'chart',
      title: 'Quarterly Revenue by Segment',
      titleMode: 'manual',
      sourceId: ORDERS_SOURCE_ID,
      config: {
        chartType: 'area-stacked',
        xField: 'date',
        xGroupBy: 'quarter',
        yField: 'total',
        seriesField: 'expr-order-segment',
      },
    },
    'widget-grid4-top-customers': {
      id: 'widget-grid4-top-customers',
      kind: 'grid',
      title: 'Top Customers',
      titleMode: 'manual',
      sourceId: ORDERS_SOURCE_ID,
      config: {
        columns: [
          { fieldId: 'expr-order-company' },
          { fieldId: 'expr-order-segment' },
          { fieldId: 'expr-order-country' },
          { fieldId: 'id' },
          { fieldId: 'total' },
        ],
        gridGroupByField: 'expr-order-company',
        gridAggregations: { id: 'count', total: 'sum' },
        gridSortField: 'total',
        gridSortDirection: 'desc',
        gridSummaryFields: { total: 'sum' },
        crossFilterField: 'expr-order-company',
      },
    },
    'widget-text-analytics': {
      id: 'widget-text-analytics',
      kind: 'text',
      title: 'Sales Analytics',
      titleMode: 'manual' as const,
      sourceId: undefined,
      config: {
        textTitleFontSize: 32,
        textTitleAlign: 'center' as const,
      },
    },
    'widget-map-revenue-by-country': {
      id: 'widget-map-revenue-by-country',
      kind: 'map',
      title: 'Revenue by Country',
      titleMode: 'manual',
      sourceId: ORDERS_SOURCE_ID,
      config: {
        mapCountryField: 'expr-order-country',
        mapValueField: 'total',
        mapAggregation: 'sum',
        mapGeography: 'world',
        mapColorScheme: 'blues',
        mapLegendZeroMin: true,
        mapCrossFilterEmit: true,
      },
    },
    'widget-pivot-revenue-by-segment': {
      id: 'widget-pivot-revenue-by-segment',
      kind: 'pivot',
      title: 'Revenue by Segment × Status',
      titleMode: 'manual',
      sourceId: ORDERS_SOURCE_ID,
      config: {
        pivotRowField: 'expr-order-segment',
        pivotColField: 'status',
        pivotValueField: 'total',
        pivotAggregation: 'sum',
        pivotShowTotals: true,
      },
    },
    'widget-chart-revenue-gauge': {
      id: 'widget-chart-revenue-gauge',
      kind: 'chart',
      title: 'Total Revenue',
      titleMode: 'manual',
      sourceId: ORDERS_SOURCE_ID,
      config: {
        chartType: 'gauge',
        yField: 'total',
        yAggregation: 'sum',
        gaugeMin: 0,
        gaugeMax: 500000,
      },
    },
    'widget-chart2-discount-heatmap': {
      id: 'widget-chart2-discount-heatmap',
      kind: 'chart',
      title: 'Quantity by Category & Discount',
      titleMode: 'manual',
      sourceId: ORDER_ITEMS_SOURCE_ID,
      config: {
        chartType: 'heatmap',
        xField: 'category',
        heatYField: 'discount',
        yField: 'quantity',
        yAggregation: 'sum',
        heatColorScheme: 'primary',
      },
    },
    'widget-chart3-delivery-heatmap': {
      id: 'widget-chart3-delivery-heatmap',
      kind: 'chart',
      title: 'Avg Delivery Days by Carrier & Month',
      titleMode: 'manual',
      sourceId: SHIPMENTS_SOURCE_ID,
      config: {
        chartType: 'heatmap',
        xField: 'shipDate',
        xGroupBy: 'month',
        heatYField: 'carrier',
        yField: 'expr-shipment-delivery-days',
        yAggregation: 'avg',
        heatColorScheme: 'warning',
      },
    },
    'widget-chart5-order-funnel': {
      id: 'widget-chart5-order-funnel',
      kind: 'chart',
      title: 'Orders by Status',
      titleMode: 'manual',
      sourceId: ORDERS_SOURCE_ID,
      config: {
        chartType: 'bar',
        xField: 'status',
        yField: 'total',
        yAggregation: 'count',
        chartSortBy: 'category' as const,
        barLayout: 'horizontal' as const,
      },
    },
    'widget-chart5-revenue-mixed': {
      id: 'widget-chart5-revenue-mixed',
      kind: 'chart',
      title: 'Revenue & Avg Discount by Category',
      titleMode: 'manual',
      sourceId: ORDER_ITEMS_SOURCE_ID,
      config: {
        chartType: 'mixed',
        xField: 'category',
        ySeries: [
          { fieldId: 'total', label: 'Revenue', type: 'bar', yAggregation: 'sum' },
          { fieldId: 'discount', label: 'Avg Discount %', type: 'line', yAggregation: 'avg' },
        ],
        dualYAxis: true,
      },
    },

    // Cross-source blend: revenue lives in Order Items, stock lives in Products —
    // two independent tables aligned on the shared `category` axis. Each series
    // carries its own sourceId and is aggregated in its own source.
    'widget-chart5-revenue-vs-stock-blend': {
      id: 'widget-chart5-revenue-vs-stock-blend',
      kind: 'chart',
      title: 'Revenue vs Inventory Stock by Category (blended sources)',
      titleMode: 'manual',
      sourceId: ORDER_ITEMS_SOURCE_ID,
      config: {
        chartType: 'mixed',
        xField: 'category',
        ySeries: [
          {
            fieldId: 'total',
            sourceId: ORDER_ITEMS_SOURCE_ID,
            label: 'Revenue (orders)',
            type: 'bar',
            yAggregation: 'sum',
          },
          {
            fieldId: 'stock',
            sourceId: PRODUCTS_SOURCE_ID,
            label: 'Stock (products)',
            type: 'line',
            yAggregation: 'sum',
          },
        ],
        dualYAxis: true,
      },
    },

    // ── Page 6: CRM Pipeline ────────────────────────────────────────────────

    'widget-text-crm-pipeline': {
      id: 'widget-text-crm-pipeline',
      kind: 'text',
      title: 'CRM Pipeline',
      titleMode: 'manual' as const,
      sourceId: undefined,
      config: {
        textTitleFontSize: 32,
        textTitleAlign: 'center' as const,
      },
    },
    'widget-kpi6-open-deals': {
      id: 'widget-kpi6-open-deals',
      kind: 'kpi',
      // Counts rows, so the value field is just a (reproducible) source anchor — point
      // it at a visible string field rather than the hidden `id`. The count ignores the
      // field, but trend/sparkline require a non-empty value field, so it can't be empty.
      title: 'Open Deals',
      sourceId: CRM_DEALS_SOURCE_ID,
      config: {
        kpiValueField: 'title',
        kpiAggregation: 'count',
        kpiTrend: true,
        kpiSparkline: true,
        kpiSparklineField: 'openedDate',
        kpiSparklinePlotType: 'bar',
        kpiSparklineGranularity: 'month',
      },
    },
    'widget-kpi6-pipeline-value': {
      id: 'widget-kpi6-pipeline-value',
      kind: 'kpi',
      title: 'Pipeline Value',
      sourceId: CRM_DEALS_SOURCE_ID,
      config: {
        kpiValueField: 'value',
        kpiAggregation: 'sum',
        kpiCompact: true,
        kpiTrend: true,
        kpiSparkline: true,
        kpiSparklineField: 'openedDate',
        kpiSparklinePlotType: 'line',
        kpiSparklineGranularity: 'quarter',
      },
    },
    'widget-kpi6-win-rate': {
      id: 'widget-kpi6-win-rate',
      kind: 'kpi',
      title: 'Avg Probability',
      sourceId: CRM_DEALS_SOURCE_ID,
      config: {
        kpiValueField: 'probability',
        kpiAggregation: 'avg',
        kpiTrend: true,
      },
    },
    'widget-chart6-deals-by-stage': {
      id: 'widget-chart6-deals-by-stage',
      kind: 'chart',
      title: 'Deals by Stage (reached)',
      sourceId: CRM_DEALS_SOURCE_ID,
      config: {
        chartType: 'funnel',
        xField: 'stage',
        yField: 'id',
        yAggregation: 'count',
        chartSortBy: 'category' as const,
        // Cumulative "reached stage" mode (EBL-03): counts deals whose reached
        // depth is at or beyond each stage → monotonic by construction, never
        // > 100%. Closed Lost is excluded from the sequence and shown as a
        // separate exit stat; the donut/grid below keep the current snapshot.
        funnelReachedField: 'stageReached',
        funnelStageSequence: [
          'Prospecting',
          'Qualification',
          'Proposal',
          'Negotiation',
          'Closed Won',
        ],
        funnelExitStage: 'Closed Lost',
      },
    },
    'widget-chart6-stage-conversion': {
      id: 'widget-chart6-stage-conversion',
      kind: 'chart',
      title: 'Stage Conversion Rate',
      titleMode: 'manual' as const,
      sourceId: CRM_DEALS_SOURCE_ID,
      config: {
        // EBL-04 #1: one bar per stage transition = step-conversion %, driven by
        // the same cumulative "reached" counts as the funnel above.
        chartType: 'funnel',
        xField: 'stage',
        yField: 'id',
        funnelReachedField: 'stageReached',
        funnelStageSequence: [
          'Prospecting',
          'Qualification',
          'Proposal',
          'Negotiation',
          'Closed Won',
        ],
        funnelExitStage: 'Closed Lost',
        funnelConversionBar: true,
      },
    },
    'widget-chart6-time-in-stage': {
      id: 'widget-chart6-time-in-stage',
      kind: 'chart',
      title: 'Avg Days in Stage by Owner',
      titleMode: 'manual' as const,
      sourceId: CRM_DEALS_SOURCE_ID,
      config: {
        // EBL-04 #3: time-in-stage heatmap. NOTE (approximation): the heatmap
        // reads one row per deal, so `daysInStage` is a per-deal *scalar* (days
        // in the deal's current/snapshot stage), not a full per-stage matrix.
        // The heatmap x-axis follows the `stage` field's `orderedValues`
        // (Prospecting→Closed Won, Closed Lost last), so stage columns appear in
        // pipeline order rather than A–Z.
        chartType: 'heatmap',
        xField: 'stage',
        heatYField: 'owner',
        yField: 'daysInStage',
        yAggregation: 'avg',
        heatColorScheme: 'warning',
      },
    },
    'widget-chart6-value-by-stage': {
      id: 'widget-chart6-value-by-stage',
      kind: 'chart',
      title: 'Pipeline Value by Stage',
      sourceId: CRM_DEALS_SOURCE_ID,
      config: {
        chartType: 'donut',
        xField: 'stage',
        yField: 'value',
      },
    },
    'widget-chart6-stage-flow': {
      id: 'widget-chart6-stage-flow',
      kind: 'chart',
      title: 'Deal Stage Flow',
      sourceId: CRM_DEAL_TRANSITIONS_SOURCE_ID,
      config: {
        chartType: 'sankey',
        xField: 'from_stage',
        sankeyTargetField: 'to_stage',
        yField: 'deal_count',
        sankeyLinkColor: 'source',
        sankeyShowValues: true,
      },
    },
    'widget-grid6-deals': {
      id: 'widget-grid6-deals',
      kind: 'grid',
      title: 'All Deals',
      sourceId: CRM_DEALS_SOURCE_ID,
      config: {
        columns: [
          { fieldId: 'title' },
          { fieldId: 'stage' },
          { fieldId: 'value' },
          { fieldId: 'probability' },
          { fieldId: 'openedDate' },
          { fieldId: 'closeDate' },
        ],
        gridSortField: 'value',
        gridSortDirection: 'desc' as const,
        gridSummaryFields: { value: 'sum', probability: 'avg' },
      },
    },

    // ── Page 7: CRM Contacts ────────────────────────────────────────────────

    'widget-text-crm-contacts': {
      id: 'widget-text-crm-contacts',
      kind: 'text',
      title: 'CRM Contacts',
      titleMode: 'manual' as const,
      sourceId: undefined,
      config: {
        textTitleFontSize: 32,
        textTitleAlign: 'center' as const,
      },
    },
    'widget-kpi7-total-contacts': {
      id: 'widget-kpi7-total-contacts',
      kind: 'kpi',
      title: 'Total Contacts',
      sourceId: CRM_CONTACTS_SOURCE_ID,
      config: {
        // A row count needs no value field — the count aggregation tallies rows.
        // This matches what the setup panel produces for a count KPI, so a user can
        // recreate this widget from scratch (pick the source, leave the value field
        // empty, aggregation defaults to Count).
        kpiAggregation: 'count',
        // Trend: fixed 90-day window so the headline (all-time total) is never gated
        // by a date filter. Delta shows new contacts added in the last 90 days vs the
        // 90 days before that.
        kpiTrend: true,
        kpiTrendFixedPeriod: 'quarter' as const,
        // Sparkline: show contacts added over time (monthly buckets).
        kpiSparkline: true,
        kpiSparklineField: 'createdAt',
        kpiSparklinePlotType: 'bar' as const,
        kpiSparklineGranularity: 'month' as const,
      },
    },
    'widget-kpi7-open-activities': {
      id: 'widget-kpi7-open-activities',
      kind: 'kpi',
      // Same as Open Deals: a row count anchored on a visible string field (`type`)
      // instead of the hidden `id`, so the trend/sparkline keep a value field while the
      // setup panel shows a real, reproducible selection.
      title: 'Activities Logged',
      sourceId: CRM_ACTIVITIES_SOURCE_ID,
      config: {
        kpiValueField: 'type',
        kpiAggregation: 'count',
        kpiTrend: true,
        kpiSparkline: true,
        kpiSparklineField: 'date',
        kpiSparklinePlotType: 'bar',
        kpiSparklineGranularity: 'month',
      },
    },
    'widget-chart7-contacts-by-dept': {
      id: 'widget-chart7-contacts-by-dept',
      kind: 'chart',
      title: 'Contacts by Department',
      sourceId: CRM_CONTACTS_SOURCE_ID,
      config: {
        // BL-186: fieldless row count — CRM Contacts has no visible numeric field, so this
        // counts contacts per department with no Y field (reproducible from the setup panel).
        chartType: 'bar',
        xField: 'department',
        yAggregation: 'count',
        barLayout: 'horizontal' as const,
        chartSortBy: 'value' as const,
        chartSortDirection: 'desc' as const,
      },
    },
    'widget-chart7-contacts-by-role': {
      id: 'widget-chart7-contacts-by-role',
      kind: 'chart',
      title: 'Contacts by Role',
      sourceId: CRM_CONTACTS_SOURCE_ID,
      config: {
        // BL-186: fieldless row count — counts contacts per role with no Y field.
        chartType: 'bar',
        xField: 'role',
        yAggregation: 'count',
        barLayout: 'horizontal' as const,
        chartSortBy: 'value' as const,
        chartSortDirection: 'desc' as const,
      },
    },
    'widget-grid7-contacts': {
      id: 'widget-grid7-contacts',
      kind: 'grid',
      title: 'All Contacts',
      sourceId: CRM_CONTACTS_SOURCE_ID,
      config: {
        columns: [
          { fieldId: 'firstName' },
          { fieldId: 'lastName' },
          { fieldId: 'email' },
          { fieldId: 'phone' },
          { fieldId: 'role' },
          { fieldId: 'department' },
        ],
        crossFilterField: 'department',
        gridSummaryFields: {},
      },
    },

    // ── Page 8: Customer 360 ────────────────────────────────────────────────
    // Widgets here join the CRM database (deals/contacts) to the Sales database
    // (customers) via the shared `customerId` foreign key. Expression fields
    // `expr-deal-segment` and `expr-deal-country` pull customer data from the
    // sales DB into the CRM deals source, enabling cross-database analysis.
    // Same-DB CRM expression fields (expr-deal-contact-role, expr-activity-*)
    // use SQL JOINs within the CRM database and resolve fully server-side.

    'widget-text-customer360': {
      id: 'widget-text-customer360',
      kind: 'text',
      title: 'Customer 360',
      subtitle: 'CRM pipeline data joined to sales customer records',
      titleMode: 'manual' as const,
      sourceId: undefined,
      config: {
        textTitleFontSize: 32,
        textTitleAlign: 'center' as const,
      },
    },
    'widget-kpi8-pipeline-value': {
      id: 'widget-kpi8-pipeline-value',
      kind: 'kpi',
      title: 'Total Pipeline Value',
      sourceId: CRM_DEALS_SOURCE_ID,
      config: {
        kpiValueField: 'value',
        kpiAggregation: 'sum',
        kpiCompact: true,
        kpiSparkline: true,
        kpiSparklineField: 'openedDate',
        kpiSparklinePlotType: 'bar',
        kpiSparklineGranularity: 'quarter',
      },
    },
    'widget-kpi8-avg-duration': {
      id: 'widget-kpi8-avg-duration',
      kind: 'kpi',
      title: 'Avg Activity Duration',
      subtitle: 'minutes per activity',
      sourceId: CRM_ACTIVITIES_SOURCE_ID,
      config: {
        kpiValueField: 'durationMin',
        kpiAggregation: 'avg',
        kpiSparkline: true,
        kpiSparklineField: 'date',
        kpiSparklinePlotType: 'line',
        kpiSparklineGranularity: 'month',
      },
    },
    'widget-chart8-pipeline-by-segment': {
      id: 'widget-chart8-pipeline-by-segment',
      kind: 'chart',
      title: 'Pipeline Value by Customer Segment',
      subtitle: 'CRM deals joined to sales customer segments',
      sourceId: CRM_DEALS_SOURCE_ID,
      config: {
        chartType: 'bar' as const,
        xField: 'expr-deal-segment',
        yField: 'value',
        yAggregation: 'sum' as const,
        chartSortBy: 'value' as const,
        chartSortDirection: 'desc' as const,
      },
    },
    'widget-chart8-revenue-by-segment': {
      id: 'widget-chart8-revenue-by-segment',
      kind: 'chart',
      title: 'Revenue by Customer Segment',
      subtitle: 'Orders joined to sales customer segments',
      sourceId: ORDERS_SOURCE_ID,
      config: {
        chartType: 'bar' as const,
        xField: 'expr-order-segment',
        yField: 'total',
        yAggregation: 'sum' as const,
        chartSortBy: 'value' as const,
        chartSortDirection: 'desc' as const,
      },
    },
    'widget-chart8-deals-by-country': {
      id: 'widget-chart8-deals-by-country',
      kind: 'chart',
      title: 'Pipeline Value by Customer Country',
      subtitle: 'CRM deal values joined to customer country from the sales database',
      sourceId: CRM_DEALS_SOURCE_ID,
      config: {
        chartType: 'bar' as const,
        barLayout: 'horizontal' as const,
        xField: 'expr-deal-country',
        yField: 'value',
        yAggregation: 'sum' as const,
        chartSortBy: 'value' as const,
        chartSortDirection: 'desc' as const,
      },
    },
    'widget-grid8-cross-db-deals': {
      id: 'widget-grid8-cross-db-deals',
      kind: 'grid',
      title: 'All Deals — enriched with sales customer data',
      subtitle: 'CRM deals joined to customer segment and country from the sales database',
      sourceId: CRM_DEALS_SOURCE_ID,
      config: {
        columns: [
          { fieldId: 'title' },
          { fieldId: 'stage' },
          { fieldId: 'value' },
          { fieldId: 'probability' },
          { fieldId: 'openedDate' },
          { fieldId: 'expr-deal-segment' },
          { fieldId: 'expr-deal-country' },
        ],
        gridSortField: 'value',
        gridSortDirection: 'desc' as const,
        gridSummaryFields: { value: 'sum', probability: 'avg' },
      },
    },
    'widget-chart8-pipeline-by-contact-role': {
      id: 'widget-chart8-pipeline-by-contact-role',
      kind: 'chart',
      title: 'Pipeline Value by Primary Contact Role',
      subtitle: 'CRM deals joined to primary contact role (same-database join)',
      sourceId: CRM_DEALS_SOURCE_ID,
      config: {
        chartType: 'bar' as const,
        barLayout: 'horizontal' as const,
        xField: 'expr-deal-contact-role',
        yField: 'value',
        yAggregation: 'sum' as const,
        chartSortBy: 'value' as const,
        chartSortDirection: 'desc' as const,
      },
    },
    'widget-chart8-activities-by-type': {
      id: 'widget-chart8-activities-by-type',
      kind: 'chart',
      title: 'Activities by Type',
      subtitle: 'CRM activity count broken down by interaction type',
      sourceId: CRM_ACTIVITIES_SOURCE_ID,
      config: {
        chartType: 'bar' as const,
        xField: 'type',
        yField: 'durationMin',
        yAggregation: 'count' as const,
        chartSortBy: 'value' as const,
        chartSortDirection: 'desc' as const,
      },
    },
    'widget-chart8-activities-by-outcome': {
      id: 'widget-chart8-activities-by-outcome',
      kind: 'chart',
      title: 'Activities by Outcome',
      subtitle: 'CRM activity count broken down by recorded outcome',
      sourceId: CRM_ACTIVITIES_SOURCE_ID,
      config: {
        chartType: 'donut' as const,
        xField: 'outcome',
        yField: 'durationMin',
        yAggregation: 'count' as const,
      },
    },
    'widget-chart8-activity-by-department': {
      id: 'widget-chart8-activity-by-department',
      kind: 'chart',
      title: 'Activity Count by Contact Department',
      subtitle: "Activities joined to the contact's department (same-database join)",
      sourceId: CRM_ACTIVITIES_SOURCE_ID,
      config: {
        chartType: 'bar' as const,
        xField: 'expr-activity-department',
        yField: 'durationMin',
        yAggregation: 'count' as const,
        chartSortBy: 'value' as const,
        chartSortDirection: 'desc' as const,
      },
    },
  },
  filters: [
    // Page 1 KPI date filters — "Last 12 months" window used for trend comparisons
    {
      id: 'filter-kpi-revenue-date',
      field: 'date',
      operator: 'greater_than_or_equal',
      value: {
        relative: true,
        amount: 12,
        unit: 'month',
        direction: 'past',
      } satisfies RelativeDateValue,
      scope: 'widget' as const,
      widgetId: 'widget-kpi-revenue',
      isDashboardDateRange: true as const,
      dateRangePreset: 'last_12_months' as const,
      fieldType: 'date' as const,
      filterSourceId: ORDERS_SOURCE_ID,
    },
    {
      id: 'filter-kpi-orders-date',
      field: 'date',
      operator: 'greater_than_or_equal',
      value: {
        relative: true,
        amount: 12,
        unit: 'month',
        direction: 'past',
      } satisfies RelativeDateValue,
      scope: 'widget' as const,
      widgetId: 'widget-kpi-orders',
      isDashboardDateRange: true as const,
      dateRangePreset: 'last_12_months' as const,
      fieldType: 'date' as const,
      filterSourceId: ORDERS_SOURCE_ID,
    },
    {
      id: 'filter-kpi-customers-date',
      field: 'date',
      operator: 'greater_than_or_equal',
      value: {
        relative: true,
        amount: 12,
        unit: 'month',
        direction: 'past',
      } satisfies RelativeDateValue,
      scope: 'widget' as const,
      widgetId: 'widget-kpi-customers',
      isDashboardDateRange: true as const,
      dateRangePreset: 'last_12_months' as const,
      fieldType: 'date' as const,
      filterSourceId: ORDERS_SOURCE_ID,
    },
    {
      id: 'filter-kpi-avg-discount-date',
      field: 'date',
      operator: 'greater_than_or_equal',
      value: {
        relative: true,
        amount: 12,
        unit: 'month',
        direction: 'past',
      } satisfies RelativeDateValue,
      scope: 'widget' as const,
      widgetId: 'widget-kpi-avg-discount',
      isDashboardDateRange: true as const,
      dateRangePreset: 'last_12_months' as const,
      fieldType: 'date' as const,
      filterSourceId: ORDERS_SOURCE_ID,
    },
    // Page 2 (Products) KPI date filters
    {
      id: 'filter-kpi2-margin-date',
      field: 'date',
      operator: 'greater_than_or_equal',
      value: {
        relative: true,
        amount: 12,
        unit: 'month',
        direction: 'past',
      } satisfies RelativeDateValue,
      scope: 'widget' as const,
      widgetId: 'widget-kpi2-margin',
      isDashboardDateRange: true as const,
      dateRangePreset: 'last_12_months' as const,
      fieldType: 'date' as const,
      filterSourceId: ORDERS_SOURCE_ID,
    },
    {
      id: 'filter-kpi2-units-date',
      field: 'date',
      operator: 'greater_than_or_equal',
      value: {
        relative: true,
        amount: 12,
        unit: 'month',
        direction: 'past',
      } satisfies RelativeDateValue,
      scope: 'widget' as const,
      widgetId: 'widget-kpi2-units-sold',
      isDashboardDateRange: true as const,
      dateRangePreset: 'last_12_months' as const,
      fieldType: 'date' as const,
      filterSourceId: ORDERS_SOURCE_ID,
    },
    {
      id: 'filter-stock-rank',
      field: 'product',
      filterMode: 'rank' as const,
      operator: 'equals',
      value: 10,
      rankDirection: 'bottom' as const,
      rankByField: 'stock',
      scope: 'widget' as const,
      widgetId: 'widget-chart2-stock-by-category',
      filterSourceId: PRODUCTS_SOURCE_ID,
    },
    // Page 3 (Logistics) KPI date filters
    {
      id: 'filter-kpi3-shipped-date',
      field: 'shipDate',
      operator: 'greater_than_or_equal',
      value: {
        relative: true,
        amount: 12,
        unit: 'month',
        direction: 'past',
      } satisfies RelativeDateValue,
      scope: 'widget' as const,
      widgetId: 'widget-kpi3-items-shipped',
      isDashboardDateRange: true as const,
      dateRangePreset: 'last_12_months' as const,
      fieldType: 'date' as const,
      filterSourceId: SHIPMENTS_SOURCE_ID,
    },
    {
      id: 'filter-kpi3-ontime-date',
      field: 'shipDate',
      operator: 'greater_than_or_equal',
      value: {
        relative: true,
        amount: 12,
        unit: 'month',
        direction: 'past',
      } satisfies RelativeDateValue,
      scope: 'widget' as const,
      widgetId: 'widget-kpi3-ontime',
      isDashboardDateRange: true as const,
      dateRangePreset: 'last_12_months' as const,
      fieldType: 'date' as const,
      filterSourceId: SHIPMENTS_SOURCE_ID,
    },
    {
      id: 'filter-country-rank',
      field: 'expr-order-country',
      filterMode: 'rank' as const,
      operator: 'equals',
      value: 5,
      rankDirection: 'top' as const,
      rankByField: 'total',
      scope: 'widget' as const,
      widgetId: 'widget-chart3-orders-by-country',
      filterSourceId: ORDERS_SOURCE_ID,
    },
    // Page 4 (Customers)
    {
      id: 'filter-kpi4-enterprise-segment',
      field: 'segment',
      operator: 'equals',
      value: 'Enterprise',
      scope: 'widget' as const,
      widgetId: 'widget-kpi4-enterprise',
      fieldType: 'string' as const,
      filterSourceId: CUSTOMERS_SOURCE_ID,
    },
    {
      id: 'filter-chart4-top-customers-rank',
      field: 'expr-order-company',
      filterMode: 'rank' as const,
      operator: 'equals',
      value: 12,
      rankDirection: 'top' as const,
      rankByField: 'total',
      scope: 'widget' as const,
      widgetId: 'widget-chart4-top-customers',
      filterSourceId: ORDERS_SOURCE_ID,
    },
    {
      id: 'filter-grid4-top-customers-rank',
      field: 'expr-order-company',
      filterMode: 'rank' as const,
      operator: 'equals',
      value: 20,
      rankDirection: 'top' as const,
      rankByField: 'total',
      scope: 'widget' as const,
      widgetId: 'widget-grid4-top-customers',
      filterSourceId: ORDERS_SOURCE_ID,
    },
    // Page 6 KPI date filters — "Last 12 months" window for CRM Pipeline KPIs
    {
      id: 'filter-kpi6-open-deals-date',
      field: 'openedDate',
      operator: 'greater_than_or_equal',
      value: {
        relative: true,
        amount: 12,
        unit: 'month',
        direction: 'past',
      } satisfies RelativeDateValue,
      scope: 'widget' as const,
      widgetId: 'widget-kpi6-open-deals',
      isDashboardDateRange: true as const,
      dateRangePreset: 'last_12_months' as const,
      fieldType: 'date' as const,
      filterSourceId: CRM_DEALS_SOURCE_ID,
    },
    {
      id: 'filter-kpi6-pipeline-value-date',
      field: 'openedDate',
      operator: 'greater_than_or_equal',
      value: {
        relative: true,
        amount: 12,
        unit: 'month',
        direction: 'past',
      } satisfies RelativeDateValue,
      scope: 'widget' as const,
      widgetId: 'widget-kpi6-pipeline-value',
      isDashboardDateRange: true as const,
      dateRangePreset: 'last_12_months' as const,
      fieldType: 'date' as const,
      filterSourceId: CRM_DEALS_SOURCE_ID,
    },
    {
      id: 'filter-kpi6-win-rate-date',
      field: 'openedDate',
      operator: 'greater_than_or_equal',
      value: {
        relative: true,
        amount: 12,
        unit: 'month',
        direction: 'past',
      } satisfies RelativeDateValue,
      scope: 'widget' as const,
      widgetId: 'widget-kpi6-win-rate',
      isDashboardDateRange: true as const,
      dateRangePreset: 'last_12_months' as const,
      fieldType: 'date' as const,
      filterSourceId: CRM_DEALS_SOURCE_ID,
    },
    // Page 7 KPI date filter — "Last 12 months" window for Activities Logged trend
    {
      id: 'filter-kpi7-activities-date',
      field: 'date',
      operator: 'greater_than_or_equal',
      value: {
        relative: true,
        amount: 12,
        unit: 'month',
        direction: 'past',
      } satisfies RelativeDateValue,
      scope: 'widget' as const,
      widgetId: 'widget-kpi7-open-activities',
      isDashboardDateRange: true as const,
      dateRangePreset: 'last_12_months' as const,
      fieldType: 'date' as const,
      filterSourceId: CRM_ACTIVITIES_SOURCE_ID,
    },
  ],
  expressionFields: [
    {
      id: 'expr-order-country',
      label: 'Country',
      description: 'Country of the customer who placed the order',
      sourceId: ORDERS_SOURCE_ID,
      isMeasure: false,
      type: 'string',
      expression: {
        joinSourceId: CUSTOMERS_SOURCE_ID,
        fieldId: 'country',
      },
    },
    {
      id: 'expr-order-segment',
      label: 'Segment',
      description: 'Segment of the customer who placed the order',
      sourceId: ORDERS_SOURCE_ID,
      isMeasure: false,
      type: 'string',
      expression: {
        joinSourceId: CUSTOMERS_SOURCE_ID,
        fieldId: 'segment',
      },
    },
    {
      id: 'expr-order-company',
      label: 'Company',
      description: 'Company of the customer who placed the order',
      sourceId: ORDERS_SOURCE_ID,
      isMeasure: false,
      type: 'string',
      expression: {
        joinSourceId: CUSTOMERS_SOURCE_ID,
        fieldId: 'company',
      },
    },
    {
      id: 'expr-product-inventory-value',
      label: 'Inventory Value',
      description: 'Total stock value (stock × unit price)',
      sourceId: PRODUCTS_SOURCE_ID,
      isMeasure: false,
      type: 'number',
      format: 'currency',
      expression: {
        operator: 'multiply',
        inputs: [{ id: 'stock' }, { id: 'price' }],
      },
    },
    {
      id: 'expr-product-margin',
      label: 'Unit Margin',
      description: 'Selling price minus cost per unit',
      sourceId: PRODUCTS_SOURCE_ID,
      isMeasure: false,
      type: 'number',
      format: 'currency',
      expression: {
        operator: 'subtract',
        inputs: [{ id: 'price' }, { id: 'cost' }],
      },
    },
    {
      id: 'expr-product-margin-pct',
      label: 'Margin %',
      description: 'Gross margin as a percentage of selling price',
      sourceId: PRODUCTS_SOURCE_ID,
      isMeasure: false,
      type: 'number',
      format: 'percent',
      expression: {
        operator: 'divide',
        inputs: [
          {
            operator: 'subtract',
            inputs: [{ id: 'price' }, { id: 'cost' }],
          },
          { id: 'price' },
        ],
      },
    },
    {
      id: 'expr-shipment-delivery-days',
      label: 'Delivery Days',
      description: 'Actual transit time in days (ship date → actual delivery date)',
      sourceId: SHIPMENTS_SOURCE_ID,
      isMeasure: false,
      type: 'number',
      format: 'integer',
      expression: {
        operator: 'datediff',
        inputs: [
          { type: 'string', value: 'day' },
          { id: 'shipDate' },
          { id: 'actualDeliveryDate' },
        ],
      },
    },
    // Cross-database expression fields: CRM deals → Sales customers
    // These join the CRM database to the sales customer records via `customerId`,
    // enabling CRM widgets to display and group by sales-side attributes.
    {
      id: 'expr-deal-segment',
      label: 'Customer Segment',
      description: 'Customer segment from the sales database, joined via customerId',
      sourceId: CRM_DEALS_SOURCE_ID,
      isMeasure: false,
      type: 'string',
      expression: {
        joinSourceId: CUSTOMERS_SOURCE_ID,
        fieldId: 'segment',
      },
    },
    {
      id: 'expr-deal-country',
      label: 'Customer Country',
      description: 'Customer country from the sales database, joined via customerId',
      sourceId: CRM_DEALS_SOURCE_ID,
      isMeasure: false,
      type: 'string',
      expression: {
        joinSourceId: CUSTOMERS_SOURCE_ID,
        fieldId: 'country',
      },
    },
    // Cross-database expression fields: CRM contacts → Sales customers
    {
      id: 'expr-contact-segment',
      label: 'Customer Segment',
      description: 'Customer segment from the sales database, joined via customerId',
      sourceId: CRM_CONTACTS_SOURCE_ID,
      isMeasure: false,
      type: 'string',
      expression: {
        joinSourceId: CUSTOMERS_SOURCE_ID,
        fieldId: 'segment',
      },
    },
    {
      id: 'expr-contact-country',
      label: 'Customer Country',
      description: 'Customer country from the sales database, joined via customerId',
      sourceId: CRM_CONTACTS_SOURCE_ID,
      isMeasure: false,
      type: 'string',
      expression: {
        joinSourceId: CUSTOMERS_SOURCE_ID,
        fieldId: 'country',
      },
    },
    // CRM-internal expression fields: deals → contacts (same CRM database — resolved via SQL JOIN)
    {
      id: 'expr-deal-contact-role',
      label: 'Primary Contact Role',
      description: 'Role of the primary contact on this deal',
      sourceId: CRM_DEALS_SOURCE_ID,
      isMeasure: false,
      type: 'string',
      expression: {
        joinSourceId: CRM_CONTACTS_SOURCE_ID,
        fieldId: 'role',
      },
    },
    {
      id: 'expr-deal-contact-dept',
      label: 'Primary Contact Department',
      description: 'Department of the primary contact on this deal',
      sourceId: CRM_DEALS_SOURCE_ID,
      isMeasure: false,
      type: 'string',
      expression: {
        joinSourceId: CRM_CONTACTS_SOURCE_ID,
        fieldId: 'department',
      },
    },
    // CRM-internal expression fields: activities → contacts (same CRM database — resolved via SQL JOIN)
    {
      id: 'expr-activity-department',
      label: 'Contact Department',
      description: 'Department of the contact who performed this activity',
      sourceId: CRM_ACTIVITIES_SOURCE_ID,
      isMeasure: false,
      type: 'string',
      expression: {
        joinSourceId: CRM_CONTACTS_SOURCE_ID,
        fieldId: 'department',
      },
    },
    {
      id: 'expr-activity-role',
      label: 'Contact Role',
      description: 'Role of the contact who performed this activity',
      sourceId: CRM_ACTIVITIES_SOURCE_ID,
      isMeasure: false,
      type: 'string',
      expression: {
        joinSourceId: CRM_CONTACTS_SOURCE_ID,
        fieldId: 'role',
      },
    },
    // CRM-internal expression fields: activities → deals (same CRM database — resolved via SQL JOIN)
    {
      id: 'expr-activity-deal-stage',
      label: 'Deal Stage',
      description: 'Sales stage of the deal this activity is linked to',
      sourceId: CRM_ACTIVITIES_SOURCE_ID,
      isMeasure: false,
      type: 'string',
      expression: {
        joinSourceId: CRM_DEALS_SOURCE_ID,
        fieldId: 'stage',
      },
    },
  ],
  shell: {
    openDrawers: { data: false, compose: true, filters: true },
    selectedWidgetId: null,
    selectedFieldId: null,
    selectedSourceId: null,
  },
};
